#!/usr/bin/env python3
"""
generate_powerpoint.py – GCSE Chemistry PowerPoint Generator

Assembles teaching presentations by duplicating slides from Palette.pptx and
filling in content generated by Claude AI.

Usage:
    # Full workflow (Claude generates outline + content):
    python generate_powerpoint.py --topic 4.1.1 --title "A Simple Model of the Atom" \
        --research "Research Reports by Topic/4.1.docx"

    # Skip API calls using pre-generated content JSON:
    python generate_powerpoint.py --topic 4.1.1 --content content_4_1_1.json

    # Save generated content JSON for future reuse:
    python generate_powerpoint.py --topic 4.1.1 --research "..." --save-content

Requirements:
    pip install anthropic pdfplumber python-docx --break-system-packages
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.dom.minidom
import zipfile
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR    = Path(__file__).parent
PALETTE_PATH  = SCRIPT_DIR / "Palette.pptx"
SPEC_PDF_PATH = SCRIPT_DIR / "AQA GCSE Chemistry Spec.PDF"
OUTPUT_DIR    = SCRIPT_DIR / "Generated Presentations"

CLAUDE_MODEL     = "claude-sonnet-4-6"
MAX_RESEARCH_CHARS = 40_000   # Truncate research doc to stay within context limits

# Maps content type names (as Claude tags slides) → Palette.pptx template slide file
SLIDE_VARIANTS = {
    "Title Slide":                          "slide1.xml",
    "Concept Definition":                   "slide2.xml",
    "Concept Explanation – Short":          "slide3.xml",
    "Concept Explanation With Example":     "slide4.xml",
    "Concept Explanation – Long":           "slide5.xml",
    "Real-World Application – Short":       "slide6.xml",
    "Real-World Application – Long":        "slide7.xml",
    "Visual Explanation – Small":           "slide8.xml",
    "Visual Explanation – Medium":          "slide9.xml",
    "Visual Explanation – Large":           "slide10.xml",
    "Assessment – Calculations":            "slide11.xml",
    "Assessment – Concepts (2 questions)":  "slide12.xml",
    "Assessment – Concepts (3 questions)":  "slide13.xml",
}

# Shape IDs of the "Click to reveal" answer boxes (from Palette.pptx analysis)
REVEAL_BOX_SHAPE_IDS = {
    "Assessment – Concepts (2 questions)": [3, 19],
    "Assessment – Concepts (3 questions)": [3, 19, 35],
}


# ──────────────────────────────────────────────────────────────────────────────
# PPTX PACK / UNPACK / CLEAN  (self-contained, no external scripts needed)
# ──────────────────────────────────────────────────────────────────────────────

def pptx_unpack(src: Path, dest: Path) -> None:
    """Extract a PPTX zip and pretty-print its XML files for string manipulation."""
    dest.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(src, "r") as zf:
        zf.extractall(dest)
    for xml_file in list(dest.rglob("*.xml")) + list(dest.rglob("*.rels")):
        try:
            raw = xml_file.read_bytes()
            dom = xml.dom.minidom.parseString(raw)
            xml_file.write_bytes(dom.toprettyxml(indent="  ", encoding="utf-8"))
        except Exception:
            pass  # Leave malformed XML untouched


def pptx_pack(src: Path, dest: Path) -> None:
    """Re-zip an unpacked PPTX directory back into a .pptx file.
    [Content_Types].xml must be the first entry per the OOXML spec."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    all_files = [f for f in src.rglob("*") if f.is_file()]
    # Sort so [Content_Types].xml is always written first
    ct_file = src / "[Content_Types].xml"
    ordered = ([ct_file] if ct_file in all_files else []) + \
              [f for f in all_files if f != ct_file]
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in ordered:
            zf.write(f, f.relative_to(src))


def pptx_clean(unpacked_dir: Path) -> None:
    """
    Remove slides not listed in sldIdLst plus their orphaned rels and media files.
    Mirrors the behaviour of the Cowork clean.py script.
    """
    pres_path      = unpacked_dir / "ppt" / "presentation.xml"
    pres_rels_path = unpacked_dir / "ppt" / "_rels" / "presentation.xml.rels"
    slides_dir     = unpacked_dir / "ppt" / "slides"
    rels_dir       = slides_dir / "_rels"

    if not pres_path.exists():
        return

    # Slides referenced by the current sldIdLst
    pres_content    = pres_path.read_text(encoding="utf-8")
    referenced_rids = set(re.findall(r'<p:sldId[^>]*r:id="([^"]+)"', pres_content))

    rid_to_slide: dict[str, str] = {}
    if pres_rels_path.exists():
        for m in re.finditer(
                r'<Relationship[^>]*Id="([^"]+)"[^>]*Target="slides/([^"]+)"',
                pres_rels_path.read_text(encoding="utf-8")):
            rid_to_slide[m.group(1)] = m.group(2)

    referenced_slides = {rid_to_slide[r] for r in referenced_rids if r in rid_to_slide}

    # Delete orphaned slide XML + rels
    removed: list[str] = []
    for slide_file in slides_dir.glob("slide*.xml"):
        if slide_file.name not in referenced_slides:
            slide_file.unlink()
            removed.append(slide_file.name)
            rels_file = rels_dir / f"{slide_file.name}.rels"
            if rels_file.exists():
                rels_file.unlink()

    if not removed:
        return

    # Strip orphaned entries from presentation.xml.rels
    if pres_rels_path.exists():
        rels_text = pres_rels_path.read_text(encoding="utf-8")
        for name in removed:
            rels_text = re.sub(
                rf'\s*<Relationship[^>]*Target="slides/{re.escape(name)}"[^/]*/>\s*',
                "\n", rels_text)
        pres_rels_path.write_text(rels_text, encoding="utf-8")

    # Strip orphaned Override entries from [Content_Types].xml
    ct_path = unpacked_dir / "[Content_Types].xml"
    if ct_path.exists():
        ct_text = ct_path.read_text(encoding="utf-8")
        for name in removed:
            ct_text = re.sub(
                rf'\s*<Override[^>]*PartName="/ppt/slides/{re.escape(name)}"[^/]*/>\s*',
                "\n", ct_text)
        ct_path.write_text(ct_text, encoding="utf-8")

    # Remove media files no longer referenced by any remaining slide
    referenced_media: set[str] = set()
    if rels_dir.exists():
        for rels_file in rels_dir.glob("*.rels"):
            for m in re.finditer(r'Target="\.\./media/([^"]+)"',
                                 rels_file.read_text(encoding="utf-8")):
                referenced_media.add(m.group(1))

    media_dir = unpacked_dir / "ppt" / "media"
    if media_dir.exists():
        for f in media_dir.glob("*"):
            if f.is_file() and f.name not in referenced_media:
                f.unlink()


# ──────────────────────────────────────────────────────────────────────────────
# XML UTILITIES
# ──────────────────────────────────────────────────────────────────────────────

def xml_escape(text: str) -> str:
    """Escape special characters for XML text content."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def set_shape_text(xml: str, shape_name: str, new_paragraphs_xml: str) -> str:
    """
    Replace the paragraph content in the txBody of the named shape.
    Finds the shape by its cNvPr name attribute, then replaces everything
    between <a:lstStyle/> and </p:txBody> with the new paragraphs.
    """
    # Locate shape by name
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        print(f"    ⚠  Shape '{shape_name}' not found in slide")
        return xml

    # Find txBody that belongs to THIS shape (first occurrence after name)
    txbody_start = xml.find("<p:txBody>", name_idx)
    if txbody_start == -1:
        print(f"    ⚠  No txBody found for shape '{shape_name}'")
        return xml

    # Find end of <a:lstStyle> (self-closing or explicit)
    lst_self = xml.find("<a:lstStyle/>", txbody_start)
    lst_close = xml.find("</a:lstStyle>", txbody_start)

    if lst_self != -1 and (lst_close == -1 or lst_self < lst_close):
        content_start = lst_self + len("<a:lstStyle/>")
    elif lst_close != -1:
        content_start = lst_close + len("</a:lstStyle>")
    else:
        print(f"    ⚠  No lstStyle found for shape '{shape_name}'")
        return xml

    # Find end of txBody
    txbody_end = xml.find("</p:txBody>", content_start)
    if txbody_end == -1:
        print(f"    ⚠  No </p:txBody> found for shape '{shape_name}'")
        return xml

    return (xml[:content_start]
            + "\n"
            + new_paragraphs_xml
            + "\n          "
            + xml[txbody_end:])


def clear_shape_text(xml: str, shape_name: str) -> str:
    """Remove all visible text from a shape (used to clear TEMPLATE: labels)."""
    empty = '          <a:p><a:endParaRPr lang="en-GB" dirty="0"/></a:p>'
    return set_shape_text(xml, shape_name, empty)


def remove_shape(xml: str, shape_name: str) -> str:
    """
    Completely remove a <p:sp> element by its cNvPr name.
    Used to delete the TEMPLATE: label rectangles from output slides.
    """
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        return xml  # Shape not found — nothing to do

    # Walk backwards to find the opening <p:sp>
    sp_start = xml.rfind("<p:sp>", 0, name_idx)
    if sp_start == -1:
        return xml

    # Walk forwards to find the matching </p:sp>
    sp_end = xml.find("</p:sp>", name_idx)
    if sp_end == -1:
        return xml
    sp_end += len("</p:sp>")

    return xml[:sp_start] + xml[sp_end:]


# ──────────────────────────────────────────────────────────────────────────────
# PARAGRAPH BUILDERS
# ──────────────────────────────────────────────────────────────────────────────

def para_title(text: str) -> str:
    """Simple paragraph for title placeholders (inherits master formatting)."""
    return (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" dirty="0"/>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_bullet(text: str) -> str:
    """Bullet point paragraph matching Palette.pptx body placeholder format.
    Font is inherited from the slide master (Calisto MT Body) — no explicit
    typeface declaration so the master theme font applies automatically."""
    return (
        f'          <a:p>\n'
        f'            <a:pPr marL="342900" indent="-342900">\n'
        f'              <a:spcAft><a:spcPts val="400"/></a:spcAft>\n'
        f'              <a:buSzPct val="100000"/>\n'
        f'            </a:pPr>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" dirty="0">\n'
        f'                <a:solidFill><a:srgbClr val="1A1A2E"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_text(text: str, bold: bool = False, italic: bool = False,
              color_hex: str = "1A1A2E", scheme_color: str = None) -> str:
    """Plain paragraph for text boxes (definition box, example cards, etc.)."""
    b_attr = ' b="1"' if bold else ''
    i_attr = ' i="1"' if italic else ''

    if scheme_color:
        fill_xml = f'<a:solidFill><a:schemeClr val="{scheme_color}"/></a:solidFill>'
    else:
        fill_xml = f'<a:solidFill><a:srgbClr val="{color_hex}"/></a:solidFill>'

    return (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB"{b_attr}{i_attr} dirty="0">\n'
        f'                {fill_xml}\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_reveal(text: str) -> str:
    """Italic paragraph for click-to-reveal answer boxes."""
    return (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" sz="2000" i="1" dirty="0">\n'
        f'                <a:solidFill><a:schemeClr val="tx1"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def bullets_xml(items: list) -> str:
    """Build multiple bullet paragraphs followed by an empty end paragraph."""
    paras = [para_bullet(item) for item in items]
    paras.append('          <a:p><a:endParaRPr lang="en-GB" dirty="0"/></a:p>')
    return "\n".join(paras)


# ──────────────────────────────────────────────────────────────────────────────
# ANIMATION XML
# ──────────────────────────────────────────────────────────────────────────────

def build_animation_xml(reveal_shape_ids: list) -> str:
    """
    Generate <p:timing> XML for click-to-reveal animations.
    Each shape in reveal_shape_ids starts hidden and appears on individual clicks.
    """
    # Initial hide animations (fire at slide start, delay=0)
    initial_hides = []
    for i, sid in enumerate(reveal_shape_ids):
        ctn_id = 10 + i
        initial_hides.append(
            f'                <p:set>\n'
            f'                  <p:cBhvr override="childStyle">\n'
            f'                    <p:cTn id="{ctn_id}" dur="1" fill="hold"/>\n'
            f'                    <p:tgtEl><p:spTgt spid="{sid}"/></p:tgtEl>\n'
            f'                    <p:attrNameLst>\n'
            f'                      <p:attrName>style.visibility</p:attrName>\n'
            f'                    </p:attrNameLst>\n'
            f'                  </p:cBhvr>\n'
            f'                  <p:to><p:strVal val="hidden"/></p:to>\n'
            f'                </p:set>'
        )

    # Click-reveal animations (main sequence, one click per box)
    click_effects = []
    base = 50
    for i, sid in enumerate(reveal_shape_ids):
        p1  = base + i * 10
        p2  = p1 + 1
        p3  = p1 + 2
        click_effects.append(
            f'                <p:par>\n'
            f'                  <p:cTn id="{p1}" fill="hold">\n'
            f'                    <p:stCondLst><p:cond evt="onBegin" delay="indefinite"/></p:stCondLst>\n'
            f'                    <p:childTnLst>\n'
            f'                      <p:par>\n'
            f'                        <p:cTn id="{p2}" presetID="1" presetClass="entr" presetSubtype="0"\n'
            f'                               fill="hold" grpId="{i}" nodeType="clickEffect">\n'
            f'                          <p:stCondLst><p:cond evt="begin" delay="0"/></p:stCondLst>\n'
            f'                          <p:childTnLst>\n'
            f'                            <p:set>\n'
            f'                              <p:cBhvr>\n'
            f'                                <p:cTn id="{p3}" dur="1" fill="hold"/>\n'
            f'                                <p:tgtEl><p:spTgt spid="{sid}"/></p:tgtEl>\n'
            f'                                <p:attrNameLst>\n'
            f'                                  <p:attrName>style.visibility</p:attrName>\n'
            f'                                </p:attrNameLst>\n'
            f'                              </p:cBhvr>\n'
            f'                              <p:to><p:strVal val="visible"/></p:to>\n'
            f'                            </p:set>\n'
            f'                          </p:childTnLst>\n'
            f'                        </p:cTn>\n'
            f'                      </p:par>\n'
            f'                    </p:childTnLst>\n'
            f'                  </p:cTn>\n'
            f'                </p:par>'
        )

    build_items = "\n".join(
        f'    <p:bldP spid="{sid}" grpId="{i}" uiExpand="1"/>'
        for i, sid in enumerate(reveal_shape_ids)
    )

    return (
        f'  <p:timing>\n'
        f'    <p:tnLst>\n'
        f'      <p:par>\n'
        f'        <p:cTn id="1" dur="indefinite" restart="whenNotActive" nodeType="tmRoot">\n'
        f'          <p:childTnLst>\n'
        f'            <p:par>\n'
        f'              <p:cTn id="2" fill="hold">\n'
        f'                <p:stCondLst><p:cond delay="0"/></p:stCondLst>\n'
        f'                <p:childTnLst>\n'
        + "\n".join(initial_hides) + "\n"
        f'                </p:childTnLst>\n'
        f'              </p:cTn>\n'
        f'            </p:par>\n'
        f'            <p:seq concurrent="1" nextAc="seek">\n'
        f'              <p:cTn id="3" dur="indefinite" nodeType="mainSeq">\n'
        f'                <p:childTnLst>\n'
        + "\n".join(click_effects) + "\n"
        f'                </p:childTnLst>\n'
        f'              </p:cTn>\n'
        f'              <p:prevCondLst><p:cond evt="onPrevMouseUp" delay="0"/></p:prevCondLst>\n'
        f'            </p:seq>\n'
        f'          </p:childTnLst>\n'
        f'        </p:cTn>\n'
        f'      </p:par>\n'
        f'    </p:tnLst>\n'
        f'    <p:bldLst>\n'
        + build_items + "\n"
        f'    </p:bldLst>\n'
        f'  </p:timing>'
    )


# ──────────────────────────────────────────────────────────────────────────────
# SLIDE CONTENT EDITORS  (one function per slide variant)
# ──────────────────────────────────────────────────────────────────────────────

def edit_title_slide(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_definition(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Rectangle 3",
                         para_text(slide.get("definition", ""), italic=True, color_hex="FFFFFF"))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_short(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_with_example(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = set_shape_text(xml, "Rectangle 3",
                         para_text(slide.get("example", "")))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_long(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_real_world_short(xml: str, slide: dict) -> str:
    """Real-World Application – Short: title + 2 example cards."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    examples = slide.get("examples", [])
    # Slide 6 shape names (from Palette.pptx analysis)
    slots = [("TextBox 14", "TextBox 15"), ("TextBox 22", "TextBox 23")]
    for i, (name_shape, desc_shape) in enumerate(slots):
        if i < len(examples):
            ex = examples[i]
            xml = set_shape_text(xml, name_shape,
                                 para_text(ex.get("name", ""), bold=True))
            xml = set_shape_text(xml, desc_shape,
                                 para_text(ex.get("description", "")))
    return xml


def edit_real_world_long(xml: str, slide: dict) -> str:
    """Real-World Application – Long: title + 3 example cards."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    examples = slide.get("examples", [])
    # Slide 7 shape names (from Palette.pptx analysis)
    slots = [
        ("TextBox 14", "TextBox 15"),
        ("TextBox 17", "TextBox 18"),
        ("TextBox 26", "TextBox 27"),
    ]
    for i, (name_shape, desc_shape) in enumerate(slots):
        if i < len(examples):
            ex = examples[i]
            xml = set_shape_text(xml, name_shape,
                                 para_text(ex.get("name", ""), bold=True))
            xml = set_shape_text(xml, desc_shape,
                                 para_text(ex.get("description", "")))
    return xml


def edit_visual_explanation(xml: str, slide: dict) -> str:
    """Visual Explanation – Small / Medium / Large: title + bullets."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "TextBox 7",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_assessment_calculations(xml: str, slide: dict) -> str:
    """Assessment – Calculations: title + 2 worked examples + reference table."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Rectangle 5",
                         para_text(slide.get("example1", "")))
    xml = set_shape_text(xml, "Rectangle 2",
                         para_text(slide.get("example2", "")))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_assessment_concepts(xml: str, slide: dict,
                             reveal_shape_ids: list) -> str:
    """Assessment – Concepts: title + 2 or 3 click-to-reveal question blocks."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")

    questions = slide.get("questions", [])

    # (type_label_shape, question_text_shape, reveal_box_shape)
    q_slots = [
        ("TextBox 14", "TextBox 15", "Rectangle 2"),    # Q1
        ("TextBox 16", "TextBox 17", "Rectangle 18"),   # Q2
        ("TextBox 32", "TextBox 33", "Rectangle 34"),   # Q3 (slide13 only)
    ]

    for i, (type_sh, q_sh, ans_sh) in enumerate(q_slots):
        if i >= len(questions):
            break
        q = questions[i]
        q_type  = q.get("type", "Explain")
        q_text  = q.get("question", "")
        q_ans   = q.get("answer", "")

        xml = set_shape_text(xml, type_sh, para_text(q_type, bold=True))
        xml = set_shape_text(xml, q_sh, para_text(q_text))

        if q_type == "Fill in the blank":
            reveal_text = f"\U0001f5b1  Click to reveal  \u2192  Answer: {q_ans}"
        else:
            reveal_text = f"\U0001f5b1  Click to reveal  \u2192  Model answer: {q_ans}"
        xml = set_shape_text(xml, ans_sh, para_reveal(reveal_text))

    # Inject animation timing XML (before </p:sld>)
    anim = build_animation_xml(reveal_shape_ids)
    xml = xml.replace("</p:sld>", f"{anim}\n</p:sld>")
    return xml


# Dispatcher table
SLIDE_EDITORS = {
    "Title Slide":                         edit_title_slide,
    "Concept Definition":                  edit_concept_definition,
    "Concept Explanation – Short":         edit_concept_explanation_short,
    "Concept Explanation With Example":    edit_concept_explanation_with_example,
    "Concept Explanation – Long":          edit_concept_explanation_long,
    "Real-World Application – Short":      edit_real_world_short,
    "Real-World Application – Long":       edit_real_world_long,
    "Visual Explanation – Small":          edit_visual_explanation,
    "Visual Explanation – Medium":         edit_visual_explanation,
    "Visual Explanation – Large":          edit_visual_explanation,
    "Assessment – Calculations":           edit_assessment_calculations,
    "Assessment – Concepts (2 questions)": lambda x, s: edit_assessment_concepts(
        x, s, REVEAL_BOX_SHAPE_IDS["Assessment – Concepts (2 questions)"]),
    "Assessment – Concepts (3 questions)": lambda x, s: edit_assessment_concepts(
        x, s, REVEAL_BOX_SHAPE_IDS["Assessment – Concepts (3 questions)"]),
}


def apply_slide_content(slide_path: Path, slide: dict) -> None:
    slide_type = slide.get("type", "")
    editor = SLIDE_EDITORS.get(slide_type)
    if editor is None:
        print(f"    ⚠  No editor for type '{slide_type}' – leaving as template placeholder")
        return
    xml = slide_path.read_text(encoding="utf-8")
    xml = editor(xml, slide)
    slide_path.write_text(xml, encoding="utf-8")


# ──────────────────────────────────────────────────────────────────────────────
# SLIDE DUPLICATION HELPERS
# ──────────────────────────────────────────────────────────────────────────────

def duplicate_slide(unpacked_dir: Path, source_filename: str, next_slide_id: int):
    """
    Duplicate a template slide from Palette.pptx into the working directory.
    next_slide_id must be provided by the caller (tracked externally to avoid
    re-reading stale presentation.xml during a batch of duplications).
    Returns (new_filename, new_rel_id).
    """
    slides_dir = unpacked_dir / "ppt" / "slides"
    rels_dir   = slides_dir / "_rels"

    # Next available slide number (from filesystem, always accurate)
    existing = [
        int(m.group(1))
        for f in slides_dir.glob("slide*.xml")
        if (m := re.match(r"slide(\d+)\.xml", f.name))
    ]
    next_num  = max(existing) + 1 if existing else 1
    dest_name = f"slide{next_num}.xml"

    # Copy slide XML
    shutil.copy2(slides_dir / source_filename, slides_dir / dest_name)

    # Copy + clean up .rels (drop notes slide references)
    src_rels  = rels_dir / f"{source_filename}.rels"
    dest_rels = rels_dir / f"{dest_name}.rels"
    if src_rels.exists():
        shutil.copy2(src_rels, dest_rels)
        content = dest_rels.read_text(encoding="utf-8")
        content = re.sub(
            r'\s*<Relationship[^>]*Type="[^"]*notesSlide"[^>]*/>\s*', "\n", content)
        dest_rels.write_text(content, encoding="utf-8")

    # Register in [Content_Types].xml
    ct_path = unpacked_dir / "[Content_Types].xml"
    ct = ct_path.read_text(encoding="utf-8")
    if f"/ppt/slides/{dest_name}" not in ct:
        ct = ct.replace(
            "</Types>",
            f'  <Override PartName="/ppt/slides/{dest_name}" '
            f'ContentType="application/vnd.openxmlformats-officedocument.'
            f'presentationml.slide+xml"/>\n</Types>')
        ct_path.write_text(ct, encoding="utf-8")

    # Add relationship to presentation.xml.rels
    pres_rels_path = unpacked_dir / "ppt" / "_rels" / "presentation.xml.rels"
    pres_rels = pres_rels_path.read_text(encoding="utf-8")
    rid_nums  = [int(m) for m in re.findall(r'Id="rId(\d+)"', pres_rels)]
    new_rid   = f"rId{max(rid_nums) + 1 if rid_nums else 1}"
    if f"slides/{dest_name}" not in pres_rels:
        new_rel = (
            f'<Relationship Id="{new_rid}" '
            f'Type="http://schemas.openxmlformats.org/officeDocument/'
            f'2006/relationships/slide" '
            f'Target="slides/{dest_name}"/>')
        pres_rels = pres_rels.replace(
            "</Relationships>", f"  {new_rel}\n</Relationships>")
        pres_rels_path.write_text(pres_rels, encoding="utf-8")

    return dest_name, new_rid


def update_slide_id_list(unpacked_dir: Path,
                         output_slides: list[tuple[int, str]]) -> None:
    """
    Rewrite the <p:sldIdLst> in presentation.xml to include ONLY
    the output slides (removing the original 13 template slides).
    output_slides: list of (slide_id, rel_id) tuples in presentation order.
    """
    pres_path = unpacked_dir / "ppt" / "presentation.xml"
    pres_xml  = pres_path.read_text(encoding="utf-8")

    new_entries = "\n".join(
        f'      <p:sldId id="{sid}" r:id="{rid}"/>'
        for sid, rid in output_slides
    )
    new_lst = f"    <p:sldIdLst>\n{new_entries}\n    </p:sldIdLst>"

    pres_xml = re.sub(
        r"<p:sldIdLst>.*?</p:sldIdLst>",
        new_lst,
        pres_xml,
        flags=re.DOTALL,
    )
    pres_path.write_text(pres_xml, encoding="utf-8")


# ──────────────────────────────────────────────────────────────────────────────
# POWERPOINT ASSEMBLY
# ──────────────────────────────────────────────────────────────────────────────

def build_powerpoint(content: dict, output_path: Path) -> None:
    """
    Main assembly function.
    1. Unpack Palette.pptx
    2. Duplicate the right template slide for each output slide
    3. Rewrite sldIdLst (remove templates, keep only output slides)
    4. Fill content in each duplicated slide
    5. Clean orphaned files (removes original 13 template slides)
    6. Pack to output .pptx
    """
    work_dir = Path(tempfile.mkdtemp(prefix="pptx_gen_"))
    print(f"\n  Working dir: {work_dir}")

    try:
        # ── Step 1: Unpack Palette.pptx ──────────────────────────────────────
        print("  📦 Unpacking Palette.pptx …")
        pptx_unpack(PALETTE_PATH, work_dir)

        slides_dir = work_dir / "ppt" / "slides"

        # Read initial max slide ID once (before any duplication changes presentation.xml)
        pres_xml_text = (work_dir / "ppt" / "presentation.xml").read_text(encoding="utf-8")
        existing_sld_ids = [
            int(m) for m in re.findall(r'<p:sldId[^>]*id="(\d+)"', pres_xml_text)
        ]
        next_slide_id = max(existing_sld_ids) + 1 if existing_sld_ids else 256

        # ── Step 2: Duplicate template slides ────────────────────────────────
        print(f"  🔄 Duplicating {len(content['slides'])} slides …")
        output_info: list[tuple[str, int, str, dict]] = []  # (filename, sid, rid, slide_dict)

        for slide in content["slides"]:
            slide_type    = slide.get("type", "")
            template_file = SLIDE_VARIANTS.get(slide_type)
            if template_file is None:
                print(f"    ⚠  Unknown type '{slide_type}' – skipping")
                continue

            dest_name, new_rid = duplicate_slide(work_dir, template_file, next_slide_id)
            output_info.append((dest_name, next_slide_id, new_rid, slide))
            print(f"    Slide {slide.get('slide_number', '?'):2}  "
                  f"[{slide_type}]  →  {dest_name}  (id={next_slide_id})")
            next_slide_id += 1

        # ── Step 3: Rewrite sldIdLst ──────────────────────────────────────────
        print("  📋 Updating slide order …")
        update_slide_id_list(
            work_dir,
            [(sid, rid) for _, sid, rid, _ in output_info]
        )

        # ── Step 4: Fill in slide content ─────────────────────────────────────
        print("  ✏️  Writing slide content …")
        for dest_name, _, _, slide in output_info:
            slide_path = slides_dir / dest_name
            print(f"    Slide {slide.get('slide_number', '?'):2}  "
                  f"[{slide.get('type', '')}]")
            apply_slide_content(slide_path, slide)

        # ── Step 5: Clean orphaned files (removes template slides 1–13) ───────
        print("  🧹 Cleaning …")
        pptx_clean(work_dir)

        # ── Step 6: Pack to output ────────────────────────────────────────────
        print(f"  📦 Packing → {output_path.name} …")
        pptx_pack(work_dir, output_path)

        print(f"\n  ✅ Saved: {output_path}")

    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


# ──────────────────────────────────────────────────────────────────────────────
# CONTENT GENERATION (Claude API)
# ──────────────────────────────────────────────────────────────────────────────

def extract_research_section(research_path: Path, topic_code: str) -> str | None:
    """
    Extract only the portion of a .docx research document relevant to topic_code.

    Collects all paragraphs under headings whose text starts with topic_code or
    any of its sub-headings (e.g. for '4.1.1' this captures '4.1.1', '4.1.1.1',
    '4.1.1.2', etc.).  Stops as soon as a heading with a *different* numbered
    topic code is encountered (e.g. '4.1.2').

    Non-numbered headings (e.g. 'Key facts', 'Required practical') that appear
    inside the section are included — they are sub-sections of the topic, not
    markers of a new topic.

    Returns None if python-docx is unavailable or no matching headings are found,
    in which case the caller falls back to reading the full document.
    """
    try:
        from docx import Document
    except ImportError:
        return None

    escaped = re.escape(topic_code)
    # Matches "4.1.1", "4.1.1.1", "4.1.1.2", etc.
    topic_re     = re.compile(rf'^\s*{escaped}(\.\d+)*\b')
    # Matches any numbered heading (used to detect the start of a different topic)
    any_topic_re = re.compile(r'^\s*\d+\.\d+')

    doc = Document(research_path)
    collected = []
    in_section = False

    for para in doc.paragraphs:
        is_heading = para.style.name.startswith("Heading")
        text = para.text.strip()
        if not text:
            continue

        if is_heading:
            if topic_re.match(text):
                in_section = True
                collected.append(f"\n{text}\n")
            elif in_section and any_topic_re.match(text):
                # Hit the next numbered topic — we're done
                break
            elif in_section:
                # A non-numbered sub-heading still inside our section
                collected.append(f"\n{text}\n")
        elif in_section:
            collected.append(text)

    return "\n".join(collected) if collected else None


def load_research_text(research_path: Path, topic_code: str = None) -> str:
    """
    Convert research document to plain text for feeding to the Claude API.

    If topic_code is provided and the file is a .docx, attempts to extract only
    the section relevant to that topic (e.g. all headings/content under 4.1.1.*).
    Falls back to reading the full document if extraction finds nothing.
    """
    if research_path.suffix.lower() in (".docx", ".doc"):
        # Attempt targeted section extraction first
        if topic_code:
            section = extract_research_section(research_path, topic_code)
            if section:
                print(f"  📖 Extracted {len(section):,} chars for topic "
                      f"{topic_code} from research doc")
                return section
            else:
                print(f"  ⚠  No headings matching '{topic_code}' found in research doc "
                      f"— using full document")

        # Fall back to full pandoc conversion
        result = subprocess.run(
            ["pandoc", str(research_path), "-t", "plain", "--wrap=none"],
            capture_output=True, text=True, encoding="utf-8", errors="replace"
        )
        if result.returncode != 0:
            raise RuntimeError(f"pandoc failed: {result.stderr}")
        return result.stdout

    return research_path.read_text(encoding="utf-8", errors="replace")


def extract_spec_section(topic_code: str) -> str:
    """Extract the relevant section from the AQA spec PDF."""
    try:
        import pdfplumber
        text_pages = []
        in_section = False
        parts = topic_code.split(".")
        # Pattern for next section at same level, e.g. 4.1.2 when we want 4.1.1
        next_section_re = re.compile(
            rf'{re.escape(parts[0])}\.{re.escape(parts[1])}\.\d+')

        with pdfplumber.open(SPEC_PDF_PATH) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text() or ""
                if topic_code in page_text:
                    in_section = True
                if in_section:
                    text_pages.append(page_text)
                    # Stop when we hit the NEXT topic at the same level
                    hits = next_section_re.findall(page_text)
                    hits = [h for h in hits if h != topic_code]
                    if hits and len(text_pages) > 1:
                        break

        return "\n".join(text_pages)
    except Exception as e:
        print(f"  ⚠  Could not extract spec section ({e}); continuing without it.")
        return ""


OUTLINE_SYSTEM = (
    "You are an expert GCSE Chemistry teacher designing PowerPoint lessons for AQA GCSE. "
    "You always ensure ALL AQA specification learning objectives are covered fully. "
    "Output valid JSON only—no markdown, no explanation."
)

OUTLINE_PROMPT = """\
Design a slide outline for AQA GCSE Chemistry topic {topic_code}: {topic_title}.

AQA specification content for this topic:
{spec_text}

Research document (excerpt):
{research_text}

AVAILABLE SLIDE TYPES (pick the best fit for each concept):
- Title Slide
- Concept Definition         (image placeholder + 1-sentence definition box + 3–4 bullets)
- Concept Explanation – Short        (3–4 bullets, no image)
- Concept Explanation With Example   (3–4 bullets + 1 example box)
- Concept Explanation – Long         (5–7 bullets for dense topics)
- Real-World Application – Short     (2 real-world example cards with brown border)
- Real-World Application – Long      (3 real-world example cards with brown border)
- Visual Explanation – Small         (large image + 3 interpretation bullets)
- Visual Explanation – Medium        (large image + 2 interpretation bullets)
- Visual Explanation – Large         (full-width image + 1 key takeaway)
- Assessment – Calculations          (2 worked examples + reference data table)
- Assessment – Concepts (2 questions)  (2 click-to-reveal questions)
- Assessment – Concepts (3 questions)  (3 click-to-reveal questions)

RULES:
1. Slide 1 MUST be "Title Slide"
2. The total number of slides MUST NOT exceed {max_slides} — this is a hard limit
3. Cover the most important learning objectives from the specification within that limit — prioritise depth over breadth if necessary
4. Include at least 2 assessment slides
5. Use Visual Explanation slides for diagrams, models, graphs, lab setups
6. Use Real-World Application slides to ground abstract chemistry in everyday examples
7. Each slide covers ONE focused concept

Output JSON:
{{
  "topic_code": "{topic_code}",
  "topic_title": "{topic_title}",
  "slides": [
    {{"slide_number": 1, "type": "Title Slide", "title": "...", "brief_description": "..."}},
    ...
  ]
}}"""

CONTENT_SYSTEM = (
    "You are a GCSE Chemistry teacher writing slide content for 14–16 year olds. "
    "Content must be accurate, specification-aligned, and age-appropriate. "
    "Output valid JSON only—no markdown, no explanation."
)

CONTENT_PROMPT = """\
Generate complete slide content for every slide in the approved outline below.

Research document (excerpt):
{research_text}

Approved outline:
{outline_json}

MANDATORY FORMATTING RULES — apply to ALL text in every field without exception:

1. BULLET POINTS: Every bullet must be a complete sentence. Do not end any bullet with a full stop (period).
2. NO HYPHENS OR DASHES: Do not use hyphens, en dashes, or em dashes anywhere — not in bullets, titles, definitions, examples, questions, answers, or any other field. Rewrite any sentence that would naturally use a dash so it reads fluently without one.
3. NO BLOCK CAPITALS for emphasis: Only use capitals where scientifically required, e.g. chemical formulas (NaOH, H2SO4, CO2). Never capitalise a whole word for emphasis.
4. TONE: Friendly, formal, and accessible to a 15-year-old student. Avoid jargon unless required by the specification; always define new terms when they are first introduced.
5. CALCULATIONS: Always include units at every step of a worked example, not just the final answer. Write units in full where possible (e.g. g/mol, not just mol) so the student can see how units cancel. For example: Moles of NaOH = 100 g divided by 40 g/mol = 2.5 mol.
6. DEPTH: The most important criterion is comprehensive coverage of the specification learning objectives. Do not compress content — if a concept requires more detail, provide it.

Output a JSON object with a "slides" array. Use this EXACT schema per slide type:

Title Slide:
  {{"slide_number": N, "type": "Title Slide", "title": "TOPIC_CODE – TOPIC_TITLE"}}

Concept Definition:
  {{"slide_number": N, "type": "Concept Definition", "title": "...",
    "definition": "One complete sentence definition.",
    "bullets": ["fact 1", "fact 2", "fact 3"]}}

Concept Explanation – Short:
  {{"slide_number": N, "type": "Concept Explanation – Short", "title": "...",
    "bullets": ["point 1", "point 2", "point 3", "point 4"]}}

Concept Explanation With Example:
  {{"slide_number": N, "type": "Concept Explanation With Example", "title": "...",
    "bullets": ["point 1", "point 2", "point 3"],
    "example": "Example name: 2–3 sentence description."}}

Concept Explanation – Long:
  {{"slide_number": N, "type": "Concept Explanation – Long", "title": "...",
    "bullets": ["point 1", "point 2", "point 3", "point 4", "point 5", "point 6"]}}

Real-World Application – Short:
  {{"slide_number": N, "type": "Real-World Application – Short", "title": "...",
    "examples": [
      {{"name": "Example Name", "description": "2 to 3 sentences."}},
      {{"name": "Example Name", "description": "2 to 3 sentences."}}
    ]}}

Real-World Application – Long:
  {{"slide_number": N, "type": "Real-World Application – Long", "title": "...",
    "examples": [
      {{"name": "...", "description": "..."}},
      {{"name": "...", "description": "..."}},
      {{"name": "...", "description": "..."}}
    ]}}

Visual Explanation – Small / Medium / Large:
  {{"slide_number": N, "type": "Visual Explanation – Small", "title": "...",
    "image_description": "Describe the diagram for image search.",
    "bullets": ["observation 1", "observation 2", "observation 3"]}}
  (3 bullets for Small, 2 for Medium, 1 for Large)

Assessment – Calculations:
  {{"slide_number": N, "type": "Assessment – Calculations", "title": "...",
    "example1": "Worked example 1 with numbered steps.",
    "example2": "Worked example 2 with numbered steps.",
    "reference_data": [["Symbol", "Name", "Value"], ["e", "Electron charge", "1.6×10⁻¹⁹ C"]]}}

Assessment – Concepts (2 questions):
  {{"slide_number": N, "type": "Assessment – Concepts (2 questions)",
    "title": "Understanding Check: TOPIC",
    "questions": [
      {{"type": "Fill in the blank",
        "question": "Sentence with a ________ to complete.",
        "answer": "correct word or phrase"}},
      {{"type": "Explain",
        "question": "Why / How question.",
        "answer": "2 to 3 sentence model answer."}}
    ]}}

Assessment – Concepts (3 questions):
  (same as above but with 3 question objects)

Full JSON:"""


def strip_json_fences(text: str) -> str:
    """Remove markdown code fences if Claude wrapped output in them."""
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


def generate_outline(client, topic_code: str, topic_title: str,
                     research_path: Path, max_slides: int = 25) -> dict:
    print("  Calling Claude API for outline …")
    research_text = load_research_text(research_path, topic_code)[:MAX_RESEARCH_CHARS]
    spec_text     = extract_spec_section(topic_code)[:10_000]

    msg = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=8192,
        system=OUTLINE_SYSTEM,
        messages=[{"role": "user", "content": OUTLINE_PROMPT.format(
            topic_code=topic_code,
            topic_title=topic_title,
            spec_text=spec_text,
            research_text=research_text,
            max_slides=max_slides,
        )}],
    )
    if msg.stop_reason == "max_tokens":
        raise RuntimeError(
            "Outline response was cut off (hit max_tokens limit). "
            "The topic may be unusually large — try splitting it or reducing MAX_RESEARCH_CHARS.")
    outline = json.loads(strip_json_fences(msg.content[0].text))

    # Hard enforcement: trim to max_slides if Claude went slightly over
    slides = outline.get("slides", [])
    if len(slides) > max_slides:
        print(f"  ⚠  Outline had {len(slides)} slides — trimming to {max_slides}")
        outline["slides"] = slides[:max_slides]

    return outline


def review_outline_interactive(outline: dict) -> bool:
    """Display outline and request approval in the terminal."""
    print("\n" + "═" * 65)
    print(f"  OUTLINE: {outline['topic_code']} – {outline['topic_title']}")
    print("═" * 65)
    for s in outline["slides"]:
        print(f"  {s['slide_number']:2d}. [{s['type']}]  {s['title']}")
        if desc := s.get("brief_description"):
            print(f"       {desc}")
    print("═" * 65)

    while True:
        answer = input("\nApprove this outline? [y = yes / n = quit]: ").strip().lower()
        if answer == "y":
            return True
        if answer in ("n", "q"):
            return False


def generate_content(client, outline: dict, research_path: Path) -> dict:
    print("  Calling Claude API for full content (may take a minute) …")
    research_text = load_research_text(
        research_path, outline.get("topic_code"))[:MAX_RESEARCH_CHARS]

    msg = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=16384,
        system=CONTENT_SYSTEM,
        messages=[{"role": "user", "content": CONTENT_PROMPT.format(
            research_text=research_text,
            outline_json=json.dumps(outline, indent=2),
        )}],
    )
    if msg.stop_reason == "max_tokens":
        raise RuntimeError(
            "Content response was cut off (hit max_tokens limit). "
            "The outline may have too many slides — try approving a shorter outline, "
            "or reduce MAX_RESEARCH_CHARS.")
    return json.loads(strip_json_fences(msg.content[0].text))


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate GCSE Chemistry PowerPoints from AQA research material."
    )
    parser.add_argument("--topic",   required=True,
                        help="Topic code, e.g. 4.1.1")
    parser.add_argument("--title",   default="",
                        help="Topic title (optional)")
    parser.add_argument("--research",
                        help="Path to research document (.docx or .txt)")
    parser.add_argument("--content",
                        help="Pre-generated content JSON (skips Claude API calls)")
    parser.add_argument("--output",
                        help="Output .pptx path (default: Generated Presentations/TOPIC.pptx)")
    parser.add_argument("--save-content", action="store_true",
                        help="Save generated content JSON alongside the .pptx")
    parser.add_argument("--max-slides", type=int, default=25,
                        help="Maximum number of slides in the outline (default: 25)")
    args = parser.parse_args()

    # Determine output path
    topic_safe   = args.topic.replace(".", "_")
    output_path  = Path(args.output) if args.output \
        else OUTPUT_DIR / f"{topic_safe}.pptx"

    print(f"\n🔬  GCSE Chemistry PowerPoint Generator")
    print(f"    Topic  : {args.topic}{(' – ' + args.title) if args.title else ''}")
    print(f"    Output : {output_path}\n")

    # ── Load or generate content ──────────────────────────────────────────────
    if args.content:
        print(f"📄 Loading content from {args.content} …")
        content = json.loads(Path(args.content).read_text(encoding="utf-8"))

    else:
        if not args.research:
            parser.error("--research is required when --content is not provided.")

        research_path = Path(args.research)
        if not research_path.is_absolute():
            research_path = SCRIPT_DIR / research_path

        try:
            import anthropic
            client = anthropic.Anthropic()
        except ImportError:
            sys.exit("❌ anthropic package not installed. Run: pip install anthropic")

        # Call 1: Generate outline
        outline = generate_outline(client, args.topic, args.title,
                                   research_path, args.max_slides)

        # User review
        approved = review_outline_interactive(outline)
        if not approved:
            print("Outline not approved. Exiting.")
            sys.exit(0)

        # Call 2: Generate full content
        content = generate_content(client, outline, research_path)

        # Optionally save content JSON
        if args.save_content:
            content_path = output_path.with_suffix(".content.json")
            content_path.write_text(json.dumps(content, indent=2), encoding="utf-8")
            print(f"  💾 Content saved to: {content_path}")

    # ── Assemble PowerPoint ───────────────────────────────────────────────────
    print("\n🔧 Assembling PowerPoint …")
    build_powerpoint(content, output_path)


if __name__ == "__main__":
    main()
