#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_powerpoint.py – GCSE Chemistry PowerPoint Generator

Assembles teaching presentations by duplicating slides from Palette.pptx and
filling in content generated by Claude AI.

Usage:
    # Full workflow (Claude generates outline + content):
    python generate_powerpoint.py --topic 4.1.1 --title "A Simple Model of the Atom" \
        --research "Research Reports by Topic/4.1.docx"

    # Skip API calls using pre-generated content JSON:
    python generate_powerpoint.py --topic 4.1.1 --content content_4_1_1.json

    # Save generated content JSON for future reuse:
    python generate_powerpoint.py --topic 4.1.1 --research "..." --save-content

Requirements:
    pip install anthropic pdfplumber python-docx --break-system-packages
"""

import argparse
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.dom.minidom
import zipfile
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR    = Path(__file__).parent
PALETTE_PATH  = SCRIPT_DIR / "Palette v2.pptx"
SPEC_PDF_PATH = SCRIPT_DIR / "AQA GCSE Chemistry Spec.PDF"
OUTPUT_DIR    = SCRIPT_DIR / "Generated Presentations"

CLAUDE_MODEL     = "claude-sonnet-4-6"
MAX_RESEARCH_CHARS = 40_000   # Truncate research doc to stay within context limits
OUTLINE_MAX_TOKENS = 12_288
OUTLINE_REVIEW_MAX_TOKENS = 12_288
CONTENT_MAX_TOKENS = 24_576
TOPIC_CODE_PATTERN = r"\d+\.\d+\.\d+(?:\.\d+)?"

# Maps content type names (as Claude tags slides) → Palette v2.pptx template slide file
# Palette v2 has 12 slides (Visual Explanation variants consolidated;
# Assessment – Concepts (1 question) added).
SLIDE_VARIANTS = {
    "Title Slide":                          "slide1.xml",
    "Concept Definition":                   "slide2.xml",
    "Concept Explanation – Short":          "slide3.xml",
    "Concept Explanation With Example":     "slide4.xml",
    "Concept Explanation – Long":           "slide5.xml",
    "Real-World Application – Short":       "slide6.xml",
    "Real-World Application – Long":        "slide7.xml",
    "Visual Explanation":                   "slide8.xml",
    "Assessment – Calculations":            "slide9.xml",
    "Assessment – Concepts (1 question)":   "slide10.xml",
    "Assessment – Concepts (2 questions)":  "slide11.xml",
    "Assessment – Concepts (3 questions)":  "slide12.xml",
}

# Numeric shape IDs (spid) of the click-to-reveal answer boxes in Palette v2.
# Used by build_animation_xml() to hide boxes at slide start and reveal on click.
REVEAL_BOX_SHAPE_IDS = {
    "Assessment – Concepts (1 question)":  [19],        # Rectangle 18
    "Assessment – Concepts (2 questions)": [3, 19],     # Rectangle 2, Rectangle 18
    "Assessment – Concepts (3 questions)": [3, 35, 19], # Rectangle 2, Rectangle 34, Rectangle 18
}

# Custom Rectangle shapes that receive generated text but have no autofit set in
# the Palette v2 template (their <a:bodyPr> is self-closing with no autofit child).
# The Title and Content Placeholder 2 shapes already have <a:normAutofit/> in the
# template and are NOT listed here.
AUTOFIT_SHAPE_NAMES: frozenset = frozenset({
    "Rectangle 3",   # definition box, example box, RW Short card 1, RW Long card 1
    "Rectangle 20",  # RW Short card 2
    "Rectangle 13",  # RW Long card 2
    "Rectangle 24",  # RW Long card 3
    "Rectangle 5",   # Assessment Calculations example 1
    "Rectangle 2",   # Assessment Calculations example 2; Assessment answer Q1 (2Q, 3Q)
    "Rectangle 12",  # Assessment question box (1Q, 2Q, 3Q)
    "Rectangle 18",  # Assessment answer box (all Q slides)
    "Rectangle 30",  # Assessment question Q2 (3Q)
    "Rectangle 34",  # Assessment answer Q2 (3Q)
    "TextBox 7",     # Visual Explanation observation bullets
})

# Character limits per field — mirrors CONTENT_PROMPT Rule 7.
# Used by audit_content_lengths() to warn when generated content exceeds design limits.
FIELD_CHAR_LIMITS = {
    "definition":    100,
    "example":       120,
    "bullet_short":  130,   # Short / Definition / With Example slides
    "bullet_long":   110,   # Long slides
    "rw_name":        50,
    "rw_desc_short": 200,
    "rw_desc_long":   90,
    "question_1q":   180,
    "question_2q":   140,
    "question_3q":    90,
    "answer_1q":     220,
    "answer_2q":     180,
    "answer_3q":      90,
}


# ──────────────────────────────────────────────────────────────────────────────
# PPTX PACK / UNPACK / CLEAN  (self-contained, no external scripts needed)
# ──────────────────────────────────────────────────────────────────────────────

def pptx_unpack(src: Path, dest: Path) -> None:
    """Extract a PPTX zip and pretty-print its XML files for string manipulation."""
    dest.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(src, "r") as zf:
        zf.extractall(dest)
    for xml_file in list(dest.rglob("*.xml")) + list(dest.rglob("*.rels")):
        try:
            raw = xml_file.read_bytes()
            dom = xml.dom.minidom.parseString(raw)
            xml_file.write_bytes(dom.toprettyxml(indent="  ", encoding="utf-8"))
        except Exception:
            pass  # Leave malformed XML untouched


def pptx_pack(src: Path, dest: Path) -> None:
    """Re-zip an unpacked PPTX directory back into a .pptx file.
    [Content_Types].xml must be the first entry per the OOXML spec."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    all_files = [f for f in src.rglob("*") if f.is_file()]
    # Sort so [Content_Types].xml is always written first
    ct_file = src / "[Content_Types].xml"
    ordered = ([ct_file] if ct_file in all_files else []) + \
              [f for f in all_files if f != ct_file]
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in ordered:
            zf.write(f, f.relative_to(src))


def pptx_clean(unpacked_dir: Path) -> None:
    """
    Remove slides not listed in sldIdLst plus their orphaned rels and media files.
    Mirrors the behaviour of the Cowork clean.py script.
    """
    pres_path      = unpacked_dir / "ppt" / "presentation.xml"
    pres_rels_path = unpacked_dir / "ppt" / "_rels" / "presentation.xml.rels"
    slides_dir     = unpacked_dir / "ppt" / "slides"
    rels_dir       = slides_dir / "_rels"

    if not pres_path.exists():
        return

    # Slides referenced by the current sldIdLst
    pres_content    = pres_path.read_text(encoding="utf-8")
    referenced_rids = set(re.findall(r'<p:sldId[^>]*r:id="([^"]+)"', pres_content))

    rid_to_slide: dict[str, str] = {}
    if pres_rels_path.exists():
        for m in re.finditer(
                r'<Relationship[^>]*Id="([^"]+)"[^>]*Target="slides/([^"]+)"',
                pres_rels_path.read_text(encoding="utf-8")):
            rid_to_slide[m.group(1)] = m.group(2)

    referenced_slides = {rid_to_slide[r] for r in referenced_rids if r in rid_to_slide}

    # Delete orphaned slide XML + rels
    removed: list[str] = []
    for slide_file in slides_dir.glob("slide*.xml"):
        if slide_file.name not in referenced_slides:
            slide_file.unlink()
            removed.append(slide_file.name)
            rels_file = rels_dir / f"{slide_file.name}.rels"
            if rels_file.exists():
                rels_file.unlink()

    if not removed:
        return

    # Strip orphaned entries from presentation.xml.rels
    if pres_rels_path.exists():
        rels_text = pres_rels_path.read_text(encoding="utf-8")
        for name in removed:
            rels_text = re.sub(
                rf'\s*<Relationship[^>]*Target="slides/{re.escape(name)}"[^/]*/>\s*',
                "\n", rels_text)
        pres_rels_path.write_text(rels_text, encoding="utf-8")

    # Strip orphaned Override entries from [Content_Types].xml
    ct_path = unpacked_dir / "[Content_Types].xml"
    if ct_path.exists():
        ct_text = ct_path.read_text(encoding="utf-8")
        for name in removed:
            ct_text = re.sub(
                rf'\s*<Override[^>]*PartName="/ppt/slides/{re.escape(name)}"[^/]*/>\s*',
                "\n", ct_text)
        ct_path.write_text(ct_text, encoding="utf-8")

    # Remove media files no longer referenced by any remaining slide
    referenced_media: set[str] = set()
    if rels_dir.exists():
        for rels_file in rels_dir.glob("*.rels"):
            for m in re.finditer(r'Target="\.\./media/([^"]+)"',
                                 rels_file.read_text(encoding="utf-8")):
                referenced_media.add(m.group(1))

    media_dir = unpacked_dir / "ppt" / "media"
    if media_dir.exists():
        for f in media_dir.glob("*"):
            if f.is_file() and f.name not in referenced_media:
                f.unlink()


# ──────────────────────────────────────────────────────────────────────────────
# XML UTILITIES
# ──────────────────────────────────────────────────────────────────────────────

def xml_escape(text: str) -> str:
    """Escape special characters for XML text content."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def set_shape_text(xml: str, shape_name: str, new_paragraphs_xml: str) -> str:
    """
    Replace the paragraph content in the txBody of the named shape.
    Finds the shape by its cNvPr name attribute, then replaces everything
    between <a:lstStyle/> and </p:txBody> with the new paragraphs.
    """
    # Locate shape by name
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        print(f"    ⚠  Shape '{shape_name}' not found in slide")
        return xml

    # Find txBody that belongs to THIS shape (first occurrence after name)
    txbody_start = xml.find("<p:txBody>", name_idx)
    if txbody_start == -1:
        print(f"    ⚠  No txBody found for shape '{shape_name}'")
        return xml

    # Find end of <a:lstStyle> (self-closing or explicit)
    lst_self = xml.find("<a:lstStyle/>", txbody_start)
    lst_close = xml.find("</a:lstStyle>", txbody_start)

    if lst_self != -1 and (lst_close == -1 or lst_self < lst_close):
        content_start = lst_self + len("<a:lstStyle/>")
    elif lst_close != -1:
        content_start = lst_close + len("</a:lstStyle>")
    else:
        print(f"    ⚠  No lstStyle found for shape '{shape_name}'")
        return xml

    # Find end of txBody
    txbody_end = xml.find("</p:txBody>", content_start)
    if txbody_end == -1:
        print(f"    ⚠  No </p:txBody> found for shape '{shape_name}'")
        return xml

    return (xml[:content_start]
            + "\n"
            + new_paragraphs_xml
            + "\n          "
            + xml[txbody_end:])


def clear_shape_text(xml: str, shape_name: str) -> str:
    """Remove all visible text from a shape (used to clear TEMPLATE: labels)."""
    empty = '          <a:p><a:endParaRPr lang="en-GB" dirty="0"/></a:p>'
    return set_shape_text(xml, shape_name, empty)


def remove_shape(xml: str, shape_name: str) -> str:
    """
    Completely remove a <p:sp> element by its cNvPr name.
    Used to delete the TEMPLATE: label rectangles from output slides.
    """
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        return xml  # Shape not found — nothing to do

    # Walk backwards to find the opening <p:sp>
    sp_start = xml.rfind("<p:sp>", 0, name_idx)
    if sp_start == -1:
        return xml

    # Walk forwards to find the matching </p:sp>
    sp_end = xml.find("</p:sp>", name_idx)
    if sp_end == -1:
        return xml
    sp_end += len("</p:sp>")

    return xml[:sp_start] + xml[sp_end:]


def set_body_autofit(xml: str, shape_name: str) -> str:
    """
    Ensure a named shape uses <a:normAutofit/> in its <a:bodyPr> so PowerPoint
    shrinks text to fit rather than clipping on overflow.

    Handles both forms that appear in Palette v2:
      Self-closing: <a:bodyPr rtlCol="0" anchor="ctr"/>
                 → <a:bodyPr rtlCol="0" anchor="ctr"><a:normAutofit/></a:bodyPr>
      Open form:  <a:bodyPr><a:noAutofit/></a:bodyPr>
                 → <a:bodyPr><a:normAutofit/></a:bodyPr>

    If <a:normAutofit> is already present the shape is left untouched.
    No-ops silently if the shape is not found on this slide.

    NOTE: The Title 1 and Content Placeholder 2 shapes already have normAutofit
    in the Palette v2 template and do not need to be passed to this function.
    """
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        return xml

    # Bound the search to this shape's <p:sp> element
    sp_end = xml.find("</p:sp>", name_idx)
    search_end = sp_end if sp_end != -1 else len(xml)

    bodypr_start = xml.find("<a:bodyPr", name_idx)
    if bodypr_start == -1 or bodypr_start > search_end:
        return xml

    tag_end = xml.find(">", bodypr_start)
    if tag_end == -1:
        return xml

    is_self_closing = xml[tag_end - 1] == "/"

    if is_self_closing:
        # <a:bodyPr attrs/> → <a:bodyPr attrs><a:normAutofit/></a:bodyPr>
        opening_tag = xml[bodypr_start:tag_end - 1]  # strip trailing /
        return (xml[:bodypr_start]
                + opening_tag + "><a:normAutofit/></a:bodyPr>"
                + xml[tag_end + 1:])
    else:
        # Open form — find closing tag
        bodypr_end = xml.find("</a:bodyPr>", tag_end)
        if bodypr_end == -1:
            return xml

        inner = xml[tag_end + 1:bodypr_end]

        # normAutofit already present — leave untouched
        if "<a:normAutofit" in inner:
            return xml

        # Replace noAutofit or spAutoFit with normAutofit; otherwise append it
        if "<a:noAutofit" in inner:
            inner = re.sub(r"<a:noAutofit\s*/>", "<a:normAutofit/>", inner)
        elif "<a:spAutoFit" in inner:
            inner = re.sub(r"<a:spAutoFit\s*/>", "<a:normAutofit/>", inner)
        else:
            inner = inner.rstrip() + "\n<a:normAutofit/>\n"

        return (xml[:tag_end + 1]
                + inner
                + "</a:bodyPr>"
                + xml[bodypr_end + len("</a:bodyPr>"):])


def apply_autofit_pass(xml: str) -> str:
    """Apply normAutofit to all content rectangle shapes in a slide XML, then
    pre-calculate and set fontScale so shrinking takes effect on first open.
    Called once per slide after the content editor has run."""
    for shape_name in AUTOFIT_SHAPE_NAMES:
        xml = set_body_autofit(xml, shape_name)
        xml = update_autofit_scale(xml, shape_name)
    return xml


def _extract_for_scale(xml: str, shape_name: str):
    """
    Extract (paragraphs, cx_emu, cy_emu, sz_emu) from a named shape.

    paragraphs  – list of plain-text strings, one per <a:p>
    cx_emu      – shape width in EMU
    cy_emu      – shape height in EMU
    sz_emu      – font height in EMU (derived from first <a:rPr sz="..."> found)

    Returns None if the shape is not found or required attributes are missing.
    """
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        return None

    sp_end_idx = xml.find("</p:sp>", name_idx)
    if sp_end_idx == -1:
        return None
    sp_xml = xml[name_idx:sp_end_idx]

    # Shape extent (cx, cy) — stored in <a:ext cx="..." cy="..."/>
    ext_match = re.search(r'<a:ext\s+cx="(\d+)"\s+cy="(\d+)"', sp_xml)
    if not ext_match:
        return None
    cx_emu = int(ext_match.group(1))
    cy_emu = int(ext_match.group(2))

    # Font size from first <a:rPr sz="..."> — in hundredths of a point
    # (e.g. sz="1800" → 18 pt)
    sz_match = re.search(r'<a:rPr[^>]*\ssz="(\d+)"', sp_xml)
    if not sz_match:
        return None
    sz_hpt = int(sz_match.group(1))
    sz_emu = sz_hpt * 127  # 1/100 pt = 127 EMU  (1 pt = 12700 EMU)

    # Paragraphs: concatenate all <a:t> runs within each <a:p>
    paragraphs = []
    for p_match in re.finditer(r'<a:p>(.*?)</a:p>', sp_xml, re.DOTALL):
        runs = re.findall(r'<a:t>(.*?)</a:t>', p_match.group(1), re.DOTALL)
        paragraphs.append("".join(runs))

    return paragraphs, cx_emu, cy_emu, sz_emu


def _calc_font_scale(paragraphs: list, cx_emu: int, cy_emu: int,
                     sz_emu: int) -> int:
    """
    Estimate the fontScale (integer, 1000–100000) needed so all paragraphs
    fit inside the shape bounds.

    Conservative geometry model:
      usable width  = cx * 0.88  (OOXML shapes carry ~6% left + 6% right inset)
      char width    = sz * 0.55  (average for Calisto MT / proportional body font)
      line height   = sz * 1.35  (1.0 cap-height + 0.35 leading)
      para gap      = 57150 EMU  (≈ 4.5 pt inter-paragraph spacing in Palette v2)
      usable height = cy * 0.92  (small top/bottom inset)

    Minimum scale returned: 65000 (65 %).  Text that would need more shrinking
    than that is handled by generation-side char-limit constraints instead.
    Returns 100000 when text already fits without scaling.
    """
    USABLE_W = 0.88
    CHAR_W   = 0.55
    LINE_H   = 1.35
    PARA_GAP = 57150   # EMU
    MIN_SCALE = 65000

    usable_w = cx_emu * USABLE_W
    usable_h = cy_emu * 0.92
    chars_per_line = max(1.0, usable_w / (sz_emu * CHAR_W))
    line_h_emu     = sz_emu * LINE_H

    total_lines = 0.0
    for i, para in enumerate(paragraphs):
        stripped = para.strip()
        if not stripped:
            total_lines += 0.5   # blank paragraph = half-line gap
            continue
        total_lines += math.ceil(len(stripped) / chars_per_line)
        if i < len(paragraphs) - 1:
            total_lines += PARA_GAP / line_h_emu

    if total_lines <= 0 or usable_h <= 0:
        return 100000

    lines_available = usable_h / line_h_emu
    if total_lines <= lines_available:
        return 100000

    raw_scale = int((lines_available / total_lines) * 100000)
    return max(raw_scale, MIN_SCALE)


def update_autofit_scale(xml: str, shape_name: str) -> str:
    """
    Pre-calculate and set fontScale on the <a:normAutofit/> element of the
    named shape so that PowerPoint renders text shrunk-to-fit on first open,
    without needing any interactive recalculation.

    Must be called after set_body_autofit (which guarantees normAutofit exists).
    No-ops silently if the shape or its normAutofit element cannot be found,
    or if the calculated scale is 100000 (no shrinking needed).
    """
    extracted = _extract_for_scale(xml, shape_name)
    if extracted is None:
        return xml

    paragraphs, cx_emu, cy_emu, sz_emu = extracted
    font_scale = _calc_font_scale(paragraphs, cx_emu, cy_emu, sz_emu)

    if font_scale >= 100000:
        return xml   # text fits — leave normAutofit with no fontScale attr

    # Locate the normAutofit element within this shape's <p:sp>
    name_marker = f'name="{shape_name}"'
    name_idx = xml.find(name_marker)
    if name_idx == -1:
        return xml
    sp_end_idx = xml.find("</p:sp>", name_idx)
    search_end = sp_end_idx if sp_end_idx != -1 else len(xml)

    na_idx = xml.find("<a:normAutofit", name_idx)
    if na_idx == -1 or na_idx > search_end:
        return xml

    na_end = xml.find(">", na_idx)
    if na_end == -1:
        return xml

    new_tag = f'<a:normAutofit fontScale="{font_scale}" lnSpcReduction="0"/>'

    if xml[na_end - 1] == "/":
        # Self-closing: <a:normAutofit ... />
        return xml[:na_idx] + new_tag + xml[na_end + 1:]
    else:
        # Open form: <a:normAutofit ...>...</a:normAutofit>
        close_idx = xml.find("</a:normAutofit>", na_end)
        if close_idx == -1:
            return xml
        return xml[:na_idx] + new_tag + xml[close_idx + len("</a:normAutofit>"):]


# ──────────────────────────────────────────────────────────────────────────────
# PARAGRAPH BUILDERS
# ──────────────────────────────────────────────────────────────────────────────

def para_title(text: str) -> str:
    """Simple paragraph for title placeholders (inherits master formatting)."""
    return (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" dirty="0"/>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_bullet(text: str) -> str:
    """Bullet point paragraph matching Palette.pptx body placeholder format.
    Font is inherited from the slide master (Calisto MT Body) — no explicit
    typeface declaration so the master theme font applies automatically."""
    return (
        f'          <a:p>\n'
        f'            <a:pPr marL="342900" indent="-342900">\n'
        f'              <a:spcAft><a:spcPts val="400"/></a:spcAft>\n'
        f'              <a:buSzPct val="100000"/>\n'
        f'            </a:pPr>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" dirty="0">\n'
        f'                <a:solidFill><a:srgbClr val="1A1A2E"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_text(text: str, bold: bool = False, italic: bool = False,
              color_hex: str = "1A1A2E", scheme_color: str = None,
              center: bool = False, sz: int = 1800) -> str:
    """Plain paragraph for content rectangle text boxes.

    An explicit sz (font size in hundredths of a point) is required here rather
    than inheriting from the slide master, because master inheritance on
    non-placeholder rectangle shapes defaults to 20pt (2000) which is too large
    for content-dense boxes and — critically — prevents normAutofit from
    functioning: PowerPoint only applies normAutofit shrinking when it
    calculates the fontScale itself at edit time, and will not recalculate it
    when opening a programmatically generated file that has normAutofit set to
    100% scale (no fontScale attribute). Setting an explicit, fit-for-purpose
    font size here makes text fit reliably without needing normAutofit to
    recalculate. normAutofit on these shapes then acts as a genuine last-resort
    safety net for edge cases rather than the primary fit mechanism.

    Default sz=1800 (18pt) is a good balance: large enough to be readable,
    small enough that content within the design character limits fits
    comfortably within the shape bounds."""
    b_attr = ' b="1"' if bold else ''
    i_attr = ' i="1"' if italic else ''
    sz_attr = f' sz="{sz}"'
    ppr_xml = '            <a:pPr algn="ctr"/>\n' if center else ''

    if scheme_color:
        fill_xml = f'<a:solidFill><a:schemeClr val="{scheme_color}"/></a:solidFill>'
    else:
        fill_xml = f'<a:solidFill><a:srgbClr val="{color_hex}"/></a:solidFill>'

    return (
        f'          <a:p>\n'
        f'{ppr_xml}'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB"{sz_attr}{b_attr}{i_attr} dirty="0">\n'
        f'                {fill_xml}\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_reveal(text: str) -> str:
    """Italic paragraph for click-to-reveal answer boxes.
    sz=1800 (18pt) rather than 20pt — same reasoning as para_text: the master
    default for non-placeholder shapes is 20pt which can overflow answer boxes,
    and normAutofit will not self-correct this in a programmatically generated
    file without an interactive recalculation trigger."""
    return (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" sz="1800" i="1" dirty="0">\n'
        f'                <a:solidFill><a:schemeClr val="tx1"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(text)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )


def para_example_card(name: str, description: str) -> str:
    """Two-paragraph text for Real-World Application cards in Palette v2.
    Paragraph 1 = example name (bold).
    Paragraph 2 = description (normal weight).
    Both at 16pt to match the template's explicit font size."""
    name_para = (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" sz="1600" b="1" dirty="0">\n'
        f'                <a:solidFill><a:srgbClr val="1A1A2E"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(name)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )
    desc_para = (
        f'          <a:p>\n'
        f'            <a:r>\n'
        f'              <a:rPr lang="en-GB" sz="1600" dirty="0">\n'
        f'                <a:solidFill><a:srgbClr val="1A1A2E"/></a:solidFill>\n'
        f'              </a:rPr>\n'
        f'              <a:t>{xml_escape(description)}</a:t>\n'
        f'            </a:r>\n'
        f'          </a:p>'
    )
    return name_para + "\n" + desc_para


def bullets_xml(items: list) -> str:
    """Build multiple bullet paragraphs followed by an empty end paragraph."""
    paras = [para_bullet(item) for item in items]
    paras.append('          <a:p><a:endParaRPr lang="en-GB" dirty="0"/></a:p>')
    return "\n".join(paras)


# ──────────────────────────────────────────────────────────────────────────────
# ANIMATION XML
# ──────────────────────────────────────────────────────────────────────────────

def build_animation_xml(reveal_shape_ids: list) -> str:
    """
    Generate <p:timing> XML for click-to-reveal animations.
    Each shape in reveal_shape_ids starts hidden and appears on individual clicks.
    """
    # Initial hide animations (fire at slide start, delay=0)
    initial_hides = []
    for i, sid in enumerate(reveal_shape_ids):
        ctn_id = 10 + i
        initial_hides.append(
            f'                <p:set>\n'
            f'                  <p:cBhvr override="childStyle">\n'
            f'                    <p:cTn id="{ctn_id}" dur="1" fill="hold"/>\n'
            f'                    <p:tgtEl><p:spTgt spid="{sid}"/></p:tgtEl>\n'
            f'                    <p:attrNameLst>\n'
            f'                      <p:attrName>style.visibility</p:attrName>\n'
            f'                    </p:attrNameLst>\n'
            f'                  </p:cBhvr>\n'
            f'                  <p:to><p:strVal val="hidden"/></p:to>\n'
            f'                </p:set>'
        )

    # Click-reveal animations (main sequence, one click per box)
    click_effects = []
    base = 50
    for i, sid in enumerate(reveal_shape_ids):
        p1  = base + i * 10
        p2  = p1 + 1
        p3  = p1 + 2
        click_effects.append(
            f'                <p:par>\n'
            f'                  <p:cTn id="{p1}" fill="hold">\n'
            f'                    <p:stCondLst><p:cond evt="onBegin" delay="indefinite"/></p:stCondLst>\n'
            f'                    <p:childTnLst>\n'
            f'                      <p:par>\n'
            f'                        <p:cTn id="{p2}" presetID="1" presetClass="entr" presetSubtype="0"\n'
            f'                               fill="hold" grpId="{i}" nodeType="clickEffect">\n'
            f'                          <p:stCondLst><p:cond evt="begin" delay="0"/></p:stCondLst>\n'
            f'                          <p:childTnLst>\n'
            f'                            <p:set>\n'
            f'                              <p:cBhvr>\n'
            f'                                <p:cTn id="{p3}" dur="1" fill="hold"/>\n'
            f'                                <p:tgtEl><p:spTgt spid="{sid}"/></p:tgtEl>\n'
            f'                                <p:attrNameLst>\n'
            f'                                  <p:attrName>style.visibility</p:attrName>\n'
            f'                                </p:attrNameLst>\n'
            f'                              </p:cBhvr>\n'
            f'                              <p:to><p:strVal val="visible"/></p:to>\n'
            f'                            </p:set>\n'
            f'                          </p:childTnLst>\n'
            f'                        </p:cTn>\n'
            f'                      </p:par>\n'
            f'                    </p:childTnLst>\n'
            f'                  </p:cTn>\n'
            f'                </p:par>'
        )

    build_items = "\n".join(
        f'    <p:bldP spid="{sid}" grpId="{i}" uiExpand="1"/>'
        for i, sid in enumerate(reveal_shape_ids)
    )

    return (
        f'  <p:timing>\n'
        f'    <p:tnLst>\n'
        f'      <p:par>\n'
        f'        <p:cTn id="1" dur="indefinite" restart="whenNotActive" nodeType="tmRoot">\n'
        f'          <p:childTnLst>\n'
        f'            <p:par>\n'
        f'              <p:cTn id="2" fill="hold">\n'
        f'                <p:stCondLst><p:cond delay="0"/></p:stCondLst>\n'
        f'                <p:childTnLst>\n'
        + "\n".join(initial_hides) + "\n"
        f'                </p:childTnLst>\n'
        f'              </p:cTn>\n'
        f'            </p:par>\n'
        f'            <p:seq concurrent="1" nextAc="seek">\n'
        f'              <p:cTn id="3" dur="indefinite" nodeType="mainSeq">\n'
        f'                <p:childTnLst>\n'
        + "\n".join(click_effects) + "\n"
        f'                </p:childTnLst>\n'
        f'              </p:cTn>\n'
        f'              <p:prevCondLst><p:cond evt="onPrevMouseUp" delay="0"/></p:prevCondLst>\n'
        f'            </p:seq>\n'
        f'          </p:childTnLst>\n'
        f'        </p:cTn>\n'
        f'      </p:par>\n'
        f'    </p:tnLst>\n'
        f'    <p:bldLst>\n'
        + build_items + "\n"
        f'    </p:bldLst>\n'
        f'  </p:timing>'
    )


# ──────────────────────────────────────────────────────────────────────────────
# SLIDE CONTENT EDITORS  (one function per slide variant)
# ──────────────────────────────────────────────────────────────────────────────

def edit_title_slide(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_definition(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Rectangle 3",
                         para_text(slide.get("definition", ""), italic=True, color_hex="FFFFFF", center=True))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_short(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_with_example(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = set_shape_text(xml, "Rectangle 3",
                         para_text(slide.get("example", ""), italic=True, color_hex="FFFFFF", center=True))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_concept_explanation_long(xml: str, slide: dict) -> str:
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Content Placeholder 2",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_real_world_short(xml: str, slide: dict) -> str:
    """Real-World Application – Short: title + 2 example cards.
    Palette v2: each card is a single Rectangle (name bold + description normal,
    two paragraphs in one text box). Shape names: Rectangle 3, Rectangle 20."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    examples = slide.get("examples", [])
    slots = ["Rectangle 3", "Rectangle 20"]
    for i, text_shape in enumerate(slots):
        if i < len(examples):
            ex = examples[i]
            xml = set_shape_text(xml, text_shape,
                                 para_example_card(ex.get("name", ""),
                                                   ex.get("description", "")))
    return xml


def edit_real_world_long(xml: str, slide: dict) -> str:
    """Real-World Application – Long: title + 3 example cards.
    Palette v2: each card is a single Rectangle. Shape names: Rectangle 3,
    Rectangle 13, Rectangle 24.
    NOTE: Each card group is only 1.476 inches visible — descriptions must be
    very concise (max ~90 chars) or text will be clipped."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")
    examples = slide.get("examples", [])
    slots = ["Rectangle 3", "Rectangle 13", "Rectangle 24"]
    for i, text_shape in enumerate(slots):
        if i < len(examples):
            ex = examples[i]
            xml = set_shape_text(xml, text_shape,
                                 para_example_card(ex.get("name", ""),
                                                   ex.get("description", "")))
    return xml


def edit_visual_explanation(xml: str, slide: dict) -> str:
    """Visual Explanation – Small / Medium / Large: title + bullets."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "TextBox 7",
                         bullets_xml(slide.get("bullets", [])))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def edit_assessment_calculations(xml: str, slide: dict) -> str:
    """Assessment – Calculations: title + 2 worked examples + reference table."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = set_shape_text(xml, "Rectangle 5",
                         para_text(slide.get("example1", ""), sz=1600))
    xml = set_shape_text(xml, "Rectangle 2",
                         para_text(slide.get("example2", ""), sz=1600))
    xml = remove_shape(xml, "Rectangle 4")
    return xml


def _reveal_text(q_type: str, answer: str) -> str:
    """Format the click-to-reveal answer text based on question type."""
    if q_type == "Fill in the blank":
        return f"\U0001f5b1  Click to reveal  \u2192  Answer: {answer}"
    return f"\U0001f5b1  Click to reveal  \u2192  Model answer: {answer}"


def edit_assessment_concepts_1q(xml: str, slide: dict) -> str:
    """Assessment – Concepts (1 question): title + single click-to-reveal block.
    Palette v2 slide10 shape names:
      Rectangle 12 = question text (inside Group 5)
      Rectangle 18 = answer reveal box (inside Group 5)"""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")

    questions = slide.get("questions", [])
    if questions:
        q = questions[0]
        xml = set_shape_text(xml, "Rectangle 12", para_text(q.get("question", "")))
        xml = set_shape_text(xml, "Rectangle 18",
                             para_reveal(_reveal_text(q.get("type", "Explain"),
                                                      q.get("answer", ""))))

    anim = build_animation_xml(REVEAL_BOX_SHAPE_IDS["Assessment – Concepts (1 question)"])
    xml = xml.replace("</p:sld>", f"{anim}\n</p:sld>")
    return xml


def edit_assessment_concepts_2q(xml: str, slide: dict) -> str:
    """Assessment – Concepts (2 questions): title + 2 click-to-reveal blocks.
    Palette v2 slide11 shape names (all direct children of slide, no groups):
      Q1: Rectangle 3 (question), Rectangle 2 (answer)
      Q2: Rectangle 12 (question), Rectangle 18 (answer)"""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")

    questions = slide.get("questions", [])
    q_slots = [
        ("Rectangle 3",  "Rectangle 2"),   # Q1
        ("Rectangle 12", "Rectangle 18"),  # Q2
    ]
    for i, (q_sh, ans_sh) in enumerate(q_slots):
        if i >= len(questions):
            break
        q = questions[i]
        xml = set_shape_text(xml, q_sh, para_text(q.get("question", "")))
        xml = set_shape_text(xml, ans_sh,
                             para_reveal(_reveal_text(q.get("type", "Explain"),
                                                      q.get("answer", ""))))

    anim = build_animation_xml(REVEAL_BOX_SHAPE_IDS["Assessment – Concepts (2 questions)"])
    xml = xml.replace("</p:sld>", f"{anim}\n</p:sld>")
    return xml


def edit_assessment_concepts_3q(xml: str, slide: dict) -> str:
    """Assessment – Concepts (3 questions): title + 3 click-to-reveal blocks.
    Palette v2 slide12 shape names (each question in its own group):
      Q1 (Group 5):  Rectangle 3  (question), Rectangle 2  (answer)
      Q2 (Group 29): Rectangle 30 (question), Rectangle 34 (answer)
      Q3 (Group 28): Rectangle 12 (question), Rectangle 18 (answer)
    NOTE: Each card is only 1.378 inches tall — questions and answers must be
    very short (max ~90 chars each). Prefer Fill-in-the-blank type questions."""
    xml = set_shape_text(xml, "Title 1", para_title(slide.get("title", "")))
    xml = remove_shape(xml, "Rectangle 4")

    questions = slide.get("questions", [])
    q_slots = [
        ("Rectangle 3",  "Rectangle 2"),   # Q1
        ("Rectangle 30", "Rectangle 34"),  # Q2
        ("Rectangle 12", "Rectangle 18"),  # Q3
    ]
    for i, (q_sh, ans_sh) in enumerate(q_slots):
        if i >= len(questions):
            break
        q = questions[i]
        xml = set_shape_text(xml, q_sh, para_text(q.get("question", "")))
        xml = set_shape_text(xml, ans_sh,
                             para_reveal(_reveal_text(q.get("type", "Explain"),
                                                      q.get("answer", ""))))

    anim = build_animation_xml(REVEAL_BOX_SHAPE_IDS["Assessment – Concepts (3 questions)"])
    xml = xml.replace("</p:sld>", f"{anim}\n</p:sld>")
    return xml


# Dispatcher table — maps slide type name → editor function
SLIDE_EDITORS = {
    "Title Slide":                          edit_title_slide,
    "Concept Definition":                   edit_concept_definition,
    "Concept Explanation – Short":          edit_concept_explanation_short,
    "Concept Explanation With Example":     edit_concept_explanation_with_example,
    "Concept Explanation – Long":           edit_concept_explanation_long,
    "Real-World Application – Short":       edit_real_world_short,
    "Real-World Application – Long":        edit_real_world_long,
    "Visual Explanation":                   edit_visual_explanation,
    "Assessment – Calculations":            edit_assessment_calculations,
    "Assessment – Concepts (1 question)":   edit_assessment_concepts_1q,
    "Assessment – Concepts (2 questions)":  edit_assessment_concepts_2q,
    "Assessment – Concepts (3 questions)":  edit_assessment_concepts_3q,
}


def apply_slide_content(slide_path: Path, slide: dict) -> None:
    slide_type = slide.get("type", "")
    editor = SLIDE_EDITORS.get(slide_type)
    if editor is None:
        print(f"    ⚠  No editor for type '{slide_type}' – leaving as template placeholder")
        return
    xml = slide_path.read_text(encoding="utf-8")
    xml = editor(xml, slide)
    xml = apply_autofit_pass(xml)   # ensure content rectangles shrink on overflow
    slide_path.write_text(xml, encoding="utf-8")


# ──────────────────────────────────────────────────────────────────────────────
# SLIDE DUPLICATION HELPERS
# ──────────────────────────────────────────────────────────────────────────────

def duplicate_slide(unpacked_dir: Path, source_filename: str, next_slide_id: int):
    """
    Duplicate a template slide from Palette.pptx into the working directory.
    next_slide_id must be provided by the caller (tracked externally to avoid
    re-reading stale presentation.xml during a batch of duplications).
    Returns (new_filename, new_rel_id).
    """
    slides_dir = unpacked_dir / "ppt" / "slides"
    rels_dir   = slides_dir / "_rels"

    # Next available slide number (from filesystem, always accurate)
    existing = [
        int(m.group(1))
        for f in slides_dir.glob("slide*.xml")
        if (m := re.match(r"slide(\d+)\.xml", f.name))
    ]
    next_num  = max(existing) + 1 if existing else 1
    dest_name = f"slide{next_num}.xml"

    # Copy slide XML
    shutil.copy2(slides_dir / source_filename, slides_dir / dest_name)

    # Copy + clean up .rels (drop notes slide references)
    src_rels  = rels_dir / f"{source_filename}.rels"
    dest_rels = rels_dir / f"{dest_name}.rels"
    if src_rels.exists():
        shutil.copy2(src_rels, dest_rels)
        content = dest_rels.read_text(encoding="utf-8")
        content = re.sub(
            r'\s*<Relationship[^>]*Type="[^"]*notesSlide"[^>]*/>\s*', "\n", content)
        dest_rels.write_text(content, encoding="utf-8")

    # Register in [Content_Types].xml
    ct_path = unpacked_dir / "[Content_Types].xml"
    ct = ct_path.read_text(encoding="utf-8")
    if f"/ppt/slides/{dest_name}" not in ct:
        ct = ct.replace(
            "</Types>",
            f'  <Override PartName="/ppt/slides/{dest_name}" '
            f'ContentType="application/vnd.openxmlformats-officedocument.'
            f'presentationml.slide+xml"/>\n</Types>')
        ct_path.write_text(ct, encoding="utf-8")

    # Add relationship to presentation.xml.rels
    pres_rels_path = unpacked_dir / "ppt" / "_rels" / "presentation.xml.rels"
    pres_rels = pres_rels_path.read_text(encoding="utf-8")
    rid_nums  = [int(m) for m in re.findall(r'Id="rId(\d+)"', pres_rels)]
    new_rid   = f"rId{max(rid_nums) + 1 if rid_nums else 1}"
    if f"slides/{dest_name}" not in pres_rels:
        new_rel = (
            f'<Relationship Id="{new_rid}" '
            f'Type="http://schemas.openxmlformats.org/officeDocument/'
            f'2006/relationships/slide" '
            f'Target="slides/{dest_name}"/>')
        pres_rels = pres_rels.replace(
            "</Relationships>", f"  {new_rel}\n</Relationships>")
        pres_rels_path.write_text(pres_rels, encoding="utf-8")

    return dest_name, new_rid


def update_slide_id_list(unpacked_dir: Path,
                         output_slides: list[tuple[int, str]]) -> None:
    """
    Rewrite the <p:sldIdLst> in presentation.xml to include ONLY
    the output slides (removing the original 13 template slides).
    output_slides: list of (slide_id, rel_id) tuples in presentation order.
    """
    pres_path = unpacked_dir / "ppt" / "presentation.xml"
    pres_xml  = pres_path.read_text(encoding="utf-8")

    new_entries = "\n".join(
        f'      <p:sldId id="{sid}" r:id="{rid}"/>'
        for sid, rid in output_slides
    )
    new_lst = f"    <p:sldIdLst>\n{new_entries}\n    </p:sldIdLst>"

    pres_xml = re.sub(
        r"<p:sldIdLst>.*?</p:sldIdLst>",
        new_lst,
        pres_xml,
        flags=re.DOTALL,
    )
    pres_path.write_text(pres_xml, encoding="utf-8")


def audit_content_lengths(content: dict) -> None:
    """
    Log warnings for any text fields that exceed their design character limits
    (defined in FIELD_CHAR_LIMITS).

    This is the practical implementation of the '12pt minimum' requirement:
    normAutofit will shrink text to fit, but if content significantly exceeds
    the limits the font may drop below 12pt and become unreadable. Any field
    flagged here should be shortened before the final run.

    Note: automatic truncation is intentionally NOT implemented — silently
    cutting GCSE explanations mid-sentence risks producing inaccurate content.
    """
    overflows: list[str] = []

    for slide in content.get("slides", []):
        s_type = slide.get("type", "")
        sn     = slide.get("slide_number", "?")

        def flag(label: str, text: str, limit: int) -> None:
            if len(text) > limit:
                preview = text[:60] + ("…" if len(text) > 60 else "")
                overflows.append(
                    f"  Slide {sn} [{s_type}] {label}: "
                    f"{len(text)} chars (limit {limit}) — '{preview}'"
                )

        is_long = "Long" in s_type
        is_3q   = "3 question" in s_type
        is_2q   = "2 question" in s_type

        if defn := slide.get("definition"):
            flag("definition", defn, FIELD_CHAR_LIMITS["definition"])

        if example := slide.get("example"):
            flag("example", example, FIELD_CHAR_LIMITS["example"])

        b_limit = FIELD_CHAR_LIMITS["bullet_long" if is_long else "bullet_short"]
        for i, b in enumerate(slide.get("bullets", [])):
            flag(f"bullet[{i+1}]", b, b_limit)

        for i, ex in enumerate(slide.get("examples", [])):
            d_limit = (FIELD_CHAR_LIMITS["rw_desc_long"] if is_long
                       else FIELD_CHAR_LIMITS["rw_desc_short"])
            flag(f"example[{i+1}].name", ex.get("name", ""),
                 FIELD_CHAR_LIMITS["rw_name"])
            flag(f"example[{i+1}].description", ex.get("description", ""), d_limit)

        for i, q in enumerate(slide.get("questions", [])):
            q_limit = (FIELD_CHAR_LIMITS["question_3q"] if is_3q else
                       FIELD_CHAR_LIMITS["question_2q"] if is_2q else
                       FIELD_CHAR_LIMITS["question_1q"])
            a_limit = (FIELD_CHAR_LIMITS["answer_3q"] if is_3q else
                       FIELD_CHAR_LIMITS["answer_2q"] if is_2q else
                       FIELD_CHAR_LIMITS["answer_1q"])
            flag(f"question[{i+1}].question", q.get("question", ""), q_limit)
            flag(f"question[{i+1}].answer",   q.get("answer",   ""), a_limit)

    if overflows:
        print("\n  ⚠  CONTENT LENGTH WARNINGS — normAutofit will attempt to shrink "
              "these but font may drop below 12pt:")
        for msg in overflows:
            print(msg)
        print("     Consider regenerating the flagged slides with tighter content.\n")


# ──────────────────────────────────────────────────────────────────────────────
# POWERPOINT ASSEMBLY
# ──────────────────────────────────────────────────────────────────────────────

def build_powerpoint(content: dict, output_path: Path) -> None:
    """
    Main assembly function.
    1. Unpack Palette.pptx
    2. Duplicate the right template slide for each output slide
    3. Rewrite sldIdLst (remove templates, keep only output slides)
    4. Fill content in each duplicated slide
    5. Clean orphaned files (removes original 13 template slides)
    6. Pack to output .pptx
    """
    work_dir = Path(tempfile.mkdtemp(prefix="pptx_gen_"))
    print(f"\n  Working dir: {work_dir}")

    try:
        # ── Step 1: Unpack Palette.pptx ──────────────────────────────────────
        print("  📦 Unpacking Palette.pptx …")
        pptx_unpack(PALETTE_PATH, work_dir)

        slides_dir = work_dir / "ppt" / "slides"

        # Read initial max slide ID once (before any duplication changes presentation.xml)
        pres_xml_text = (work_dir / "ppt" / "presentation.xml").read_text(encoding="utf-8")
        existing_sld_ids = [
            int(m) for m in re.findall(r'<p:sldId[^>]*id="(\d+)"', pres_xml_text)
        ]
        next_slide_id = max(existing_sld_ids) + 1 if existing_sld_ids else 256

        # ── Step 2: Duplicate template slides ────────────────────────────────
        print(f"  🔄 Duplicating {len(content['slides'])} slides …")
        output_info: list[tuple[str, int, str, dict]] = []  # (filename, sid, rid, slide_dict)

        for slide in content["slides"]:
            slide_type    = slide.get("type", "")
            template_file = SLIDE_VARIANTS.get(slide_type)
            if template_file is None:
                print(f"    ⚠  Unknown type '{slide_type}' – skipping")
                continue

            dest_name, new_rid = duplicate_slide(work_dir, template_file, next_slide_id)
            output_info.append((dest_name, next_slide_id, new_rid, slide))
            print(f"    Slide {slide.get('slide_number', '?'):2}  "
                  f"[{slide_type}]  →  {dest_name}  (id={next_slide_id})")
            next_slide_id += 1

        # ── Step 3: Rewrite sldIdLst ──────────────────────────────────────────
        print("  📋 Updating slide order …")
        update_slide_id_list(
            work_dir,
            [(sid, rid) for _, sid, rid, _ in output_info]
        )

        # ── Step 4: Fill in slide content ─────────────────────────────────────
        print("  ✏️  Writing slide content …")
        for dest_name, _, _, slide in output_info:
            slide_path = slides_dir / dest_name
            print(f"    Slide {slide.get('slide_number', '?'):2}  "
                  f"[{slide.get('type', '')}]")
            apply_slide_content(slide_path, slide)

        # ── Step 5: Clean orphaned files (removes template slides 1–13) ───────
        print("  🧹 Cleaning …")
        pptx_clean(work_dir)

        # ── Step 6: Pack to output ────────────────────────────────────────────
        print(f"  📦 Packing → {output_path.name} …")
        pptx_pack(work_dir, output_path)

        print(f"\n  ✅ Saved: {output_path}")

    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


# ──────────────────────────────────────────────────────────────────────────────
# CONTENT GENERATION (Claude API)
# ──────────────────────────────────────────────────────────────────────────────

def extract_research_section(research_path: Path, topic_code: str) -> str | None:
    """
    Extract only the portion of a .docx research document relevant to topic_code.

    Collects all paragraphs under headings whose text starts with topic_code or
    any of its sub-headings (e.g. for '4.1.1' this captures '4.1.1', '4.1.1.1',
    '4.1.1.2', etc.).  Stops as soon as a heading with a *different* numbered
    topic code is encountered (e.g. '4.1.2').

    Non-numbered headings (e.g. 'Key facts', 'Required practical') that appear
    inside the section are included — they are sub-sections of the topic, not
    markers of a new topic.

    Returns None if python-docx is unavailable or no matching headings are found,
    in which case the caller falls back to reading the full document.
    """
    try:
        from docx import Document
    except ImportError:
        return None

    try:
        escaped = re.escape(topic_code)
        # Matches "4.1.1", "4.1.1.1", "4.1.1.2", etc.
        topic_re     = re.compile(rf'^\s*{escaped}(\.\d+)*\b')
        # Matches any numbered heading (used to detect the start of a different topic)
        any_topic_re = re.compile(r'^\s*\d+\.\d+')

        doc = Document(research_path)
        collected = []
        in_section = False

        for para in doc.paragraphs:
            is_heading = para.style.name.startswith("Heading")
            text = para.text.strip()
            if not text:
                continue

            if is_heading:
                if topic_re.match(text):
                    in_section = True
                    collected.append(f"\n{text}\n")
                elif in_section and any_topic_re.match(text):
                    # Hit the next numbered topic — we're done
                    break
                elif in_section:
                    # A non-numbered sub-heading still inside our section
                    collected.append(f"\n{text}\n")
            elif in_section:
                collected.append(text)

        return "\n".join(collected) if collected else None

    except Exception as e:
        print(f"  ⚠  Could not parse research document ({e}); falling back to full document")
        return None


def load_research_text(research_path: Path, topic_code: str = None) -> str:
    """
    Convert research document to plain text for feeding to the Claude API.

    If topic_code is provided and the file is a .docx, attempts to extract only
    the section relevant to that topic (e.g. all headings/content under 4.1.1.*).
    Falls back to reading the full document if extraction finds nothing.
    """
    if research_path.suffix.lower() in (".docx", ".doc"):
        # Attempt targeted section extraction first
        if topic_code:
            section = extract_research_section(research_path, topic_code)
            if section:
                print(f"  📖 Extracted {len(section):,} chars for topic "
                      f"{topic_code} from research doc")
                return section
            else:
                print(f"  ⚠  No headings matching '{topic_code}' found in research doc "
                      f"— using full document")

        # Fall back to full pandoc conversion
        try:
            result = subprocess.run(
                ["pandoc", str(research_path), "-t", "plain", "--wrap=none"],
                capture_output=True, text=True, encoding="utf-8", errors="replace"
            )
        except FileNotFoundError:
            raise RuntimeError(
                "pandoc is not installed or not on PATH. "
                "Install it from https://pandoc.org/installing.html and try again."
            )
        if result.returncode != 0:
            raise RuntimeError(f"pandoc failed: {result.stderr}")
        return result.stdout

    return research_path.read_text(encoding="utf-8", errors="replace")


def extract_spec_section(topic_code: str) -> str:
    """Extract the relevant section from the AQA spec PDF."""
    try:
        import pdfplumber
        text_pages = []
        in_section = False
        # Keep local validation for callers that use this helper outside main().
        if not re.fullmatch(TOPIC_CODE_PATTERN, topic_code):
            print(
                f"  ⚠  Topic code '{topic_code}' is malformed; expected format like "
                f"'4.1.1' or '4.1.1.1'. Returning empty spec text."
            )
            return ""
        parts = topic_code.split(".")
        # Pattern for next sibling at the same depth.
        # e.g. 4.1.1   → matches 4.1.2, 4.1.3 …  (stops at next top-level sub-topic)
        #      4.1.1.1 → matches 4.1.1.2, 4.1.1.3 … (stops within the parent topic only)
        parent_prefix = re.escape(".".join(parts[:-1]))
        next_section_re = re.compile(rf'{parent_prefix}\.\d+')

        with pdfplumber.open(SPEC_PDF_PATH) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text() or ""
                if topic_code in page_text:
                    in_section = True
                if in_section:
                    text_pages.append(page_text)
                    # Stop when we hit the NEXT topic at the same level
                    hits = next_section_re.findall(page_text)
                    hits = [h for h in hits if h != topic_code]
                    if hits and len(text_pages) > 1:
                        break

        return "\n".join(text_pages)
    except Exception as e:
        print(f"  ⚠  Could not extract spec section ({e}); continuing without it.")
        return ""


OUTLINE_SYSTEM = (
    "You are an expert GCSE Chemistry teacher designing PowerPoint lessons for AQA GCSE. "
    "You always ensure ALL AQA specification learning objectives are covered fully and in a "
    "student-friendly teaching sequence. "
    "Output valid JSON only—no markdown, no explanation."
)

OUTLINE_PROMPT = """\
Design a slide outline for AQA GCSE Chemistry topic {topic_code}: {topic_title}.

AQA specification content for this topic:
{spec_text}

Research document (excerpt):
{research_text}

AVAILABLE SLIDE TYPES (pick the best fit for each concept):
- Title Slide
- Concept Definition                   (1-sentence definition box + 4 supporting bullets — always first for a new concept)
- Concept Explanation – Short          (3–4 bullets, full-width — most common explanation type, prefer this)
- Concept Explanation With Example     (max 3 bullets + 1 example callout box at bottom)
- Concept Explanation – Long           (5–7 short bullets for dense multi-part topics)
- Real-World Application – Short       (2 real-world example cards — name + 2–3 sentence description each)
- Real-World Application – Long        (3 real-world example cards — name + 1 SHORT sentence each, very brief)
- Visual Explanation                   (central image placeholder + 2–3 observation bullets — image added manually)
- Assessment – Calculations            (2 worked calculation examples with numbered steps)
- Assessment – Concepts (1 question)   (1 open-ended explain question with click-to-reveal model answer)
- Assessment – Concepts (2 questions)  (2 click-to-reveal questions: Q1 fill-in-blank, Q2 explain — standard assessment)
- Assessment – Concepts (3 questions)  (3 short click-to-reveal questions — all must be very brief)

RULES:
1. Slide 1 MUST be "Title Slide"
2. Cover the full specification content shown above with enough depth for GCSE exam preparation
3. Keep the deck efficient: include only slides that add learning value, avoid repetition, and do not over-allocate slides to any single concept
4. Include at least 2 assessment slides distributed at logical points in the lesson
5. Use Visual Explanation slides for diagrams, models, graphs, lab setups
6. Use Real-World Application slides to ground abstract chemistry in everyday examples
7. Each slide covers ONE focused concept

Output JSON:
{{
  "topic_code": "{topic_code}",
  "topic_title": "{topic_title}",
  "slides": [
    {{"slide_number": 1, "type": "Title Slide", "title": "...", "brief_description": "..."}},
    ...
  ]
}}"""

OUTLINE_REVIEW_SYSTEM = (
    "You are an expert AQA GCSE Chemistry curriculum reviewer. "
    "Evaluate lesson outlines for specification coverage and student accessibility. "
    "If the outline is not good enough, revise it directly and return improved JSON. "
    "Output valid JSON only—no markdown, no explanation."
)

OUTLINE_REVIEW_PROMPT = """\
Review this draft slide outline for topic {topic_code}: {topic_title}.

AQA specification content for this topic:
{spec_text}

Research document (excerpt):
{research_text}

Current outline JSON:
{outline_json}

Review criteria (all are mandatory):
1. Comprehensive specification alignment: all required learning objectives in the provided AQA section are covered
2. Logical flow for students: concepts build clearly from foundational to more complex ideas
3. Depth calibration: key concepts are explained in sufficient depth for GCSE exam success
4. Over-explanation check: no concept is given unnecessary repetition or too many slides relative to its importance
5. Understanding checks: assessment and consolidation opportunities appear at logical intervals
6. Accessibility and tone fit: the planned learning journey is warm, encouraging, and accessible to GCSE students

Decision rules:
- If the outline fully satisfies the criteria, return decision "approve"
- If not, return decision "revise" and provide a fully revised outline that fixes all issues, then it will be reviewed again

Output schema:
{{
  "decision": "approve" | "revise",
  "review_summary": "short summary of strengths/gaps",
  "required_changes": ["change 1", "change 2"],
  "outline": {{
    "topic_code": "{topic_code}",
    "topic_title": "{topic_title}",
    "slides": [
      {{"slide_number": 1, "type": "Title Slide", "title": "...", "brief_description": "..."}},
      ...
    ]
  }}
}}

When decision is "approve", you may return the original outline in "outline".
When decision is "revise", "outline" is mandatory and must be the improved full outline."""

CONTENT_SYSTEM = (
    "You are an expert AQA GCSE Chemistry teacher writing slide content for 14–16 year olds "
    "preparing for their exams. Every bullet point, definition, and explanation must be as "
    "informative and precise as possible — include key scientific terms, units, and the level "
    "of detail a student needs to answer exam questions confidently. Accuracy and depth are the "
    "top priority, delivered with a warm, encouraging, student-friendly tone. "
    "Output valid JSON only — no markdown, no explanation."
)

CONTENT_PROMPT = """\
Generate complete slide content for every slide in the approved outline below.

Research document (excerpt):
{research_text}

Approved outline:
{outline_json}

MANDATORY FORMATTING RULES — apply to ALL text in every field without exception:

1. BULLET POINTS: Every bullet must be a complete sentence. Do not end any bullet with a full stop (period).
2. NO HYPHENS OR DASHES: Do not use hyphens, en dashes, or em dashes anywhere — not in bullets, titles, definitions, examples, questions, answers, or any other field. Rewrite any sentence that would naturally use a dash so it reads fluently without one.
3. NO BLOCK CAPITALS for emphasis: Only use capitals where scientifically required, e.g. chemical formulas (NaOH, H2SO4, CO2). Never capitalise a whole word for emphasis.
4. TONE: Warm, friendly, and accessible to a 15-year-old student. Sound like a supportive teacher, not a cold syllabus. Avoid jargon unless required by the specification; always define new terms when they are first introduced.
5. CALCULATIONS: Always include units at every step of a worked example, not just the final answer. Write units in full where possible (e.g. g/mol, not just mol) so the student can see how units cancel. For example: Moles of NaOH = 100 g divided by 40 g/mol = 2.5 mol.
6. DEPTH: The most important criterion is comprehensive coverage of the specification learning objectives. Do not compress content — if a concept requires more detail, provide it. Include precise values, units, and key terms wherever they help a student answer an exam question.
7. LENGTH TARGETS (use the full allowance — thin content leaves students underprepared; text will overflow only if you exceed the maximum):
   - definition: 80–100 characters — write a full, precise sentence
   - bullets (Short/Definition types): 100–130 characters each — aim for the upper end
   - bullets (Long type): 80–110 characters each
   - Concept Explanation With Example: max 3 bullets; example 90–120 characters
   - Real-World Application Short description: 150–200 characters per example
   - Real-World Application Long description: max 90 characters per example (cards are very small — be concise)
   - Assessment reveal answers: 120–180 characters; Assessment 3Q answers max 90 characters
   - Visual Explanation observations: max 80 characters each

Output a JSON object with a "slides" array. Use this EXACT schema per slide type:

Title Slide:
  {{"slide_number": N, "type": "Title Slide", "title": "TOPIC_CODE – TOPIC_TITLE"}}

Concept Definition:
  {{"slide_number": N, "type": "Concept Definition", "title": "...",
    "definition": "One complete sentence definition (max 100 chars).",
    "bullets": ["fact 1", "fact 2", "fact 3", "fact 4"]}}

Concept Explanation – Short:
  {{"slide_number": N, "type": "Concept Explanation – Short", "title": "...",
    "bullets": ["point 1", "point 2", "point 3", "point 4"]}}

Concept Explanation With Example:
  {{"slide_number": N, "type": "Concept Explanation With Example", "title": "...",
    "bullets": ["point 1", "point 2", "point 3"],
    "example": "One or two sentences illustrating the concept (max 120 chars)."}}

Concept Explanation – Long:
  {{"slide_number": N, "type": "Concept Explanation – Long", "title": "...",
    "bullets": ["point 1", "point 2", "point 3", "point 4", "point 5", "point 6"]}}

Real-World Application – Short:
  {{"slide_number": N, "type": "Real-World Application – Short", "title": "...",
    "examples": [
      {{"name": "Example Name (max 50 chars)", "description": "2 sentences, max 200 chars."}},
      {{"name": "Example Name (max 50 chars)", "description": "2 sentences, max 200 chars."}}
    ]}}

Real-World Application – Long:
  {{"slide_number": N, "type": "Real-World Application – Long", "title": "...",
    "examples": [
      {{"name": "Short name (max 40 chars)", "description": "One short sentence, max 90 chars."}},
      {{"name": "Short name (max 40 chars)", "description": "One short sentence, max 90 chars."}},
      {{"name": "Short name (max 40 chars)", "description": "One short sentence, max 90 chars."}}
    ]}}

Visual Explanation:
  {{"slide_number": N, "type": "Visual Explanation", "title": "...",
    "image_description": "Describe the diagram or graph for manual image sourcing.",
    "bullets": ["observation 1 (max 80 chars)", "observation 2 (max 80 chars)", "observation 3 (max 80 chars)"]}}

Assessment – Calculations:
  {{"slide_number": N, "type": "Assessment – Calculations", "title": "...",
    "example1": "Worked example 1 with numbered steps (max 400 chars).",
    "example2": "Worked example 2 with numbered steps (max 400 chars).",
    "reference_data": [["Symbol", "Name", "Value"], ["e", "Electron charge", "1.6×10⁻¹⁹ C"]]}}

Assessment – Concepts (1 question):
  {{"slide_number": N, "type": "Assessment – Concepts (1 question)",
    "title": "Understanding Check: TOPIC",
    "questions": [
      {{"type": "Explain",
        "question": "Open-ended why or how question (max 180 chars).",
        "answer": "Model answer: 2 to 3 concise sentences (max 220 chars total including prefix)."}}
    ]}}

Assessment – Concepts (2 questions):
  {{"slide_number": N, "type": "Assessment – Concepts (2 questions)",
    "title": "Understanding Check: TOPIC",
    "questions": [
      {{"type": "Fill in the blank",
        "question": "Sentence with a ________ to complete (max 100 chars).",
        "answer": "correct word or phrase (max 30 chars)"}},
      {{"type": "Explain",
        "question": "Why or how question (max 140 chars).",
        "answer": "Model answer in 1 to 2 sentences (max 180 chars total including prefix)."}}
    ]}}

Assessment – Concepts (3 questions):
  {{"slide_number": N, "type": "Assessment – Concepts (3 questions)",
    "title": "Quick Check: TOPIC",
    "questions": [
      {{"type": "Fill in the blank", "question": "Short sentence with ________ (max 90 chars).", "answer": "word (max 30 chars)"}},
      {{"type": "Fill in the blank", "question": "Short sentence with ________ (max 90 chars).", "answer": "word (max 30 chars)"}},
      {{"type": "Fill in the blank", "question": "Short sentence with ________ (max 90 chars).", "answer": "word (max 30 chars)"}}
    ]}}

Full JSON:"""


def strip_json_fences(text: str) -> str:
    """Extract the JSON object from Claude's response.

    Uses brace-finding rather than regex fence-stripping so it handles:
    - Responses with conversational preamble before the JSON block
    - Responses where closing ``` was cut off due to max_tokens
    - Responses with no fences at all
    """
    start_idx = text.find('{')
    end_idx = text.rfind('}')
    if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
        return text[start_idx:end_idx + 1]
    return text.strip()


def _require_fields(slide: dict, required_fields: list[str], where: str) -> None:
    missing = [f for f in required_fields if f not in slide]
    if missing:
        raise ValueError(f"{where} is missing required field(s): {', '.join(missing)}")


def validate_content_schema(content: dict, source_name: str) -> None:
    """Validate generated/loaded content before assembly."""
    if not isinstance(content, dict):
        raise ValueError(f"{source_name} must be a JSON object at top level.")
    slides = content.get("slides")
    if not isinstance(slides, list):
        raise ValueError(f"{source_name} must contain a 'slides' array.")

    question_min = {
        "Assessment – Concepts (1 question)": 1,
        "Assessment – Concepts (2 questions)": 2,
        "Assessment – Concepts (3 questions)": 3,
    }

    for i, slide in enumerate(slides, start=1):
        where = f"{source_name} slide #{i}"
        if not isinstance(slide, dict):
            raise ValueError(f"{where} must be an object.")

        slide_type = slide.get("type")
        if not isinstance(slide_type, str) or not slide_type:
            raise ValueError(f"{where} has missing/invalid 'type'.")
        if slide_type not in SLIDE_VARIANTS:
            raise ValueError(f"{where} has unsupported type '{slide_type}'.")

        _require_fields(slide, ["title"], where)

        if slide_type == "Title Slide":
            continue
        if slide_type == "Concept Definition":
            _require_fields(slide, ["definition", "bullets"], where)
            if not isinstance(slide["bullets"], list):
                raise ValueError(f"{where} field 'bullets' must be an array.")
        elif slide_type in ("Concept Explanation – Short", "Concept Explanation – Long"):
            _require_fields(slide, ["bullets"], where)
            if not isinstance(slide["bullets"], list):
                raise ValueError(f"{where} field 'bullets' must be an array.")
        elif slide_type == "Concept Explanation With Example":
            _require_fields(slide, ["bullets", "example"], where)
            if not isinstance(slide["bullets"], list):
                raise ValueError(f"{where} field 'bullets' must be an array.")
        elif slide_type in ("Real-World Application – Short", "Real-World Application – Long"):
            _require_fields(slide, ["examples"], where)
            examples = slide["examples"]
            if not isinstance(examples, list):
                raise ValueError(f"{where} field 'examples' must be an array.")
            for ex_i, ex in enumerate(examples, start=1):
                if not isinstance(ex, dict):
                    raise ValueError(f"{where} example #{ex_i} must be an object.")
                _require_fields(ex, ["name", "description"], f"{where} example #{ex_i}")
        elif slide_type == "Visual Explanation":
            _require_fields(slide, ["bullets"], where)
            if not isinstance(slide["bullets"], list):
                raise ValueError(f"{where} field 'bullets' must be an array.")
        elif slide_type == "Assessment – Calculations":
            _require_fields(slide, ["example1", "example2"], where)
        elif slide_type in question_min:
            _require_fields(slide, ["questions"], where)
            questions = slide["questions"]
            if not isinstance(questions, list):
                raise ValueError(f"{where} field 'questions' must be an array.")
            min_q = question_min[slide_type]
            if len(questions) < min_q:
                raise ValueError(f"{where} requires at least {min_q} question(s).")
            for q_i, q in enumerate(questions, start=1):
                if not isinstance(q, dict):
                    raise ValueError(f"{where} question #{q_i} must be an object.")
                _require_fields(q, ["question", "answer"], f"{where} question #{q_i}")


def generate_outline(client, topic_code: str, topic_title: str,
                     research_path: Path) -> dict:
    print("  Calling Claude API for outline …")
    research_text = load_research_text(research_path, topic_code)[:MAX_RESEARCH_CHARS]
    spec_text     = extract_spec_section(topic_code)[:10_000]

    msg = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=OUTLINE_MAX_TOKENS,
        system=OUTLINE_SYSTEM,
        messages=[{"role": "user", "content": OUTLINE_PROMPT.format(
            topic_code=topic_code,
            topic_title=topic_title,
            spec_text=spec_text,
            research_text=research_text,
        )}],
    )
    if msg.stop_reason == "max_tokens":
        raise RuntimeError(
            "Outline response was cut off (hit max_tokens limit). "
            "The topic may be unusually large — try splitting it or reducing MAX_RESEARCH_CHARS.")
    text_blocks = [b for b in msg.content if getattr(b, "type", None) == "text"]
    if not text_blocks:
        raise RuntimeError(
            "Claude returned no text content in the outline response. "
            f"Stop reason: {msg.stop_reason}. Content blocks: {msg.content!r}"
        )
    raw_text = strip_json_fences(text_blocks[0].text)
    try:
        outline = json.loads(raw_text)
    except json.JSONDecodeError as e:
        print("❌ Failed to parse outline JSON. The response may have been cut off mid-generation.")
        print(f"   Raw extracted text (first 500 chars):\n{raw_text[:500]}...\n")
        raise RuntimeError(f"Outline JSON parse failed: {e}") from e

    return outline


def validate_outline_schema(outline: dict) -> None:
    """Raise ValueError if the outline is missing required top-level or slide fields."""
    if not isinstance(outline, dict):
        raise ValueError("Outline must be a JSON object.")
    for field in ("topic_code", "topic_title", "slides"):
        if field not in outline:
            raise ValueError(f"Outline is missing required field '{field}'.")
    if not isinstance(outline["slides"], list) or not outline["slides"]:
        raise ValueError("Outline 'slides' must be a non-empty array.")
    for i, s in enumerate(outline["slides"], start=1):
        if not isinstance(s, dict):
            raise ValueError(f"Outline slide #{i} must be an object.")
        for field in ("slide_number", "type", "title"):
            if field not in s:
                raise ValueError(f"Outline slide #{i} is missing required field '{field}'.")
        if s["type"] not in SLIDE_VARIANTS:
            raise ValueError(
                f"Outline slide #{i} has unsupported type '{s['type']}'.")


def review_outline_interactive(outline: dict) -> bool:
    """Display outline and request approval in the terminal."""
    print("\n" + "═" * 65)
    print(f"  OUTLINE: {outline['topic_code']} – {outline['topic_title']}")
    print("═" * 65)
    for s in outline["slides"]:
        print(f"  {s['slide_number']:2d}. [{s['type']}]  {s['title']}")
        if desc := s.get("brief_description"):
            print(f"       {desc}")
    print("═" * 65)

    while True:
        answer = input("\nApprove this outline? [y = yes / n = quit]: ").strip().lower()
        if answer == "y":
            return True
        if answer in ("n", "q"):
            return False


def auto_review_outline(client, outline: dict, research_path: Path,
                        max_review_rounds: int = 3) -> dict:
    """Run iterative Claude-based outline QA until approved or review limit reached."""
    review_outline = outline
    topic_code = outline.get("topic_code", "")
    topic_title = outline.get("topic_title", "")
    research_text = load_research_text(research_path, topic_code)[:MAX_RESEARCH_CHARS]
    spec_text = extract_spec_section(topic_code)[:10_000]

    for round_num in range(1, max_review_rounds + 1):
        print(f"  Running automated outline review (round {round_num}/{max_review_rounds}) …")
        msg = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=OUTLINE_REVIEW_MAX_TOKENS,
            system=OUTLINE_REVIEW_SYSTEM,
            messages=[{"role": "user", "content": OUTLINE_REVIEW_PROMPT.format(
                topic_code=topic_code,
                topic_title=topic_title,
                spec_text=spec_text,
                research_text=research_text,
                outline_json=json.dumps(review_outline, indent=2),
            )}],
        )
        if msg.stop_reason == "max_tokens":
            raise RuntimeError(
                "Outline review response was cut off (hit max_tokens limit). "
                "Try reducing MAX_RESEARCH_CHARS or topic scope.")
        text_blocks = [b for b in msg.content if getattr(b, "type", None) == "text"]
        if not text_blocks:
            raise RuntimeError(
                "Claude returned no text content in the outline review response. "
                f"Stop reason: {msg.stop_reason}. Content blocks: {msg.content!r}"
            )
        raw_text = strip_json_fences(text_blocks[0].text)
        try:
            review_result = json.loads(raw_text)
        except json.JSONDecodeError as e:
            print("❌ Failed to parse outline review JSON.")
            print(f"   Raw extracted text (first 500 chars):\n{raw_text[:500]}...\n")
            raise RuntimeError(f"Outline review JSON parse failed: {e}") from e

        decision = str(review_result.get("decision", "")).strip().lower()
        review_summary = review_result.get("review_summary", "")
        if review_summary:
            print(f"    Review summary: {review_summary}")

        revised_outline = review_result.get("outline")
        if decision == "approve":
            if isinstance(revised_outline, dict):
                validate_outline_schema(revised_outline)
                return revised_outline
            validate_outline_schema(review_outline)
            return review_outline

        if decision == "revise":
            if not isinstance(revised_outline, dict):
                raise RuntimeError(
                    "Outline review requested revision but did not provide an outline object.")
            validate_outline_schema(revised_outline)
            review_outline = revised_outline
            continue

        raise RuntimeError(
            f"Outline review returned invalid decision '{decision}'. "
            "Expected 'approve' or 'revise'.")

    raise RuntimeError(
        "Automated outline review reached max rounds without approval. "
        "Please rerun with a narrower topic or adjust prompts.")


def generate_content(client, outline: dict, research_path: Path) -> dict:
    print("  Calling Claude API for full content (may take a minute) …")
    research_text = load_research_text(
        research_path, outline.get("topic_code"))[:MAX_RESEARCH_CHARS]

    msg = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=CONTENT_MAX_TOKENS,
        system=CONTENT_SYSTEM,
        messages=[{"role": "user", "content": CONTENT_PROMPT.format(
            research_text=research_text,
            outline_json=json.dumps(outline, indent=2),
        )}],
    )
    if msg.stop_reason == "max_tokens":
        raise RuntimeError(
            "Content response was cut off (hit max_tokens limit). "
            "Try reducing MAX_RESEARCH_CHARS or narrowing topic scope.")
    text_blocks = [b for b in msg.content if getattr(b, "type", None) == "text"]
    if not text_blocks:
        raise RuntimeError(
            "Claude returned no text content in the content response. "
            f"Stop reason: {msg.stop_reason}. Content blocks: {msg.content!r}"
        )
    raw_text = strip_json_fences(text_blocks[0].text)
    try:
        return json.loads(raw_text)
    except json.JSONDecodeError as e:
        print("❌ Failed to parse content JSON. The response may have been cut off mid-generation.")
        print(f"   Raw extracted text (first 500 chars):\n{raw_text[:500]}...\n")
        raise RuntimeError(f"Content JSON parse failed: {e}") from e


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate GCSE Chemistry PowerPoints from AQA research material."
    )
    parser.add_argument("--topic",   required=True,
                        help="Topic code, e.g. 4.1.1")
    parser.add_argument("--title",   default="",
                        help="Topic title (optional)")
    parser.add_argument("--research",
                        help="Path to research document (.docx or .txt)")
    parser.add_argument("--content",
                        help="Pre-generated content JSON (skips Claude API calls)")
    parser.add_argument("--output",
                        help="Output .pptx path (default: Generated Presentations/TOPIC.pptx)")
    parser.add_argument("--save-content", action="store_true",
                        help="Save generated content JSON alongside the .pptx")
    args = parser.parse_args()
    if not re.fullmatch(TOPIC_CODE_PATTERN, args.topic):
        sys.exit(
            "❌ Invalid --topic format. Expected X.Y.Z (or X.Y.Z.W), e.g. "
            "'4.1.1' or '4.1.1.1'."
        )

    # Determine output path
    topic_safe   = args.topic.replace(".", "_")
    output_path  = Path(args.output) if args.output \
        else OUTPUT_DIR / f"{topic_safe}.pptx"

    # ── Preflight checks ─────────────────────────────────────────────────────
    if not PALETTE_PATH.exists():
        sys.exit(
            f"❌ Template file not found: {PALETTE_PATH}\n"
            f"   Place 'Palette v2.pptx' in the same folder as this script."
        )
    if not args.content and not SPEC_PDF_PATH.exists():
        sys.exit(
            f"❌ Spec PDF not found: {SPEC_PDF_PATH}\n"
            f"   Place 'AQA GCSE Chemistry Spec.PDF' in the same folder as this script."
        )

    print(f"\n🔬  GCSE Chemistry PowerPoint Generator")
    print(f"    Topic  : {args.topic}{(' – ' + args.title) if args.title else ''}")
    print(f"    Output : {output_path}\n")

    # ── Load or generate content ──────────────────────────────────────────────
    if args.content:
        print(f"📄 Loading content from {args.content} …")
        try:
            content = json.loads(Path(args.content).read_text(encoding="utf-8"))
        except FileNotFoundError:
            sys.exit(
                f"❌ Content file not found: {args.content}\n"
                f"   Make sure the file exists in the folder you are running the script from."
            )
        except OSError as e:
            sys.exit(f"❌ Could not read content file: {e}")
        except json.JSONDecodeError as e:
            sys.exit(f"❌ Content file is not valid JSON: {e}")
        try:
            validate_content_schema(content, "--content JSON")
        except ValueError as e:
            sys.exit(f"❌ Invalid content JSON: {e}")

    else:
        if not args.research:
            parser.error("--research is required when --content is not provided.")

        research_path = Path(args.research)
        if not research_path.is_absolute():
            research_path = SCRIPT_DIR / research_path

        try:
            import anthropic
            client = anthropic.Anthropic()
        except ImportError:
            sys.exit("❌ anthropic package not installed. Run: pip install anthropic")

        # Call 1: Generate outline
        outline = generate_outline(client, args.topic, args.title,
                                   research_path)
        try:
            validate_outline_schema(outline)
        except ValueError as e:
            sys.exit(f"❌ Generated outline failed validation: {e}")

        # Automated Claude review (can revise and re-review before approval)
        try:
            outline = auto_review_outline(client, outline, research_path)
        except ValueError as e:
            sys.exit(f"❌ Auto-reviewed outline failed validation: {e}")
        except RuntimeError as e:
            sys.exit(f"❌ Automated outline review failed: {e}")

        # User review
        approved = review_outline_interactive(outline)
        if not approved:
            print("Outline not approved. Exiting.")
            sys.exit(0)

        # Call 2: Generate full content
        content = generate_content(client, outline, research_path)
        try:
            validate_content_schema(content, "generated content")
        except ValueError as e:
            sys.exit(f"❌ Generated content failed validation: {e}")

        # Optionally save content JSON
        if args.save_content:
            content_path = output_path.with_suffix(".content.json")
            content_path.parent.mkdir(parents=True, exist_ok=True)
            content_path.write_text(json.dumps(content, indent=2), encoding="utf-8")
            print(f"  💾 Content saved to: {content_path}")

    # ── Audit content lengths (12pt floor warning) ───────────────────────────
    audit_content_lengths(content)

    # ── Assemble PowerPoint ───────────────────────────────────────────────────
    print("\n🔧 Assembling PowerPoint …")
    build_powerpoint(content, output_path)


if __name__ == "__main__":
    main()
